// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Hexa.py',
//                'MooneyRivlin_Hexa_Order2.py',
//                'MooneyRivlin_Tetra.py',
//                'MooneyRivlin_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_9a8f8253e2ce3b0285ae648e6e421149bac8e316;

extern ufcx_finite_element element_e0603f46bc0d6f4cb2c9a9b00cac26c3a359e546;

extern ufcx_finite_element element_b6ab2acdf2e58dad768876dc7d1481381bb7197b;

extern ufcx_finite_element element_52431c8c0b179094cb83db4158892f74443a6c67;

extern ufcx_dofmap dofmap_9a8f8253e2ce3b0285ae648e6e421149bac8e316;

extern ufcx_dofmap dofmap_e0603f46bc0d6f4cb2c9a9b00cac26c3a359e546;

extern ufcx_dofmap dofmap_b6ab2acdf2e58dad768876dc7d1481381bb7197b;

extern ufcx_dofmap dofmap_52431c8c0b179094cb83db4158892f74443a6c67;

extern ufcx_integral integral_6224b4d4ed8d3ea7f5affd02376ddf1d98c81334;

extern ufcx_integral integral_d99438b70623b9d81c92c4de845ba540cb89117f;

extern ufcx_integral integral_d73b8ebe1c42319983c770ae35e50572cd1d8993;

extern ufcx_form form_88453d18d773548c04a63cc06cf9fe701e213b36;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Order2_F(const char* function_name);

extern ufcx_form form_76415ad43c00586acc7a133cfdd9823e755ffd3d;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Order2_J(const char* function_name);

extern ufcx_form form_b5cc1bd16647545a86262a56c83f8cfcf357c9f0;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
