// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Hexa.py',
//                'MooneyRivlin_Hexa_Order2.py',
//                'MooneyRivlin_Tetra.py',
//                'MooneyRivlin_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_635d4e60a5d12f84b092b035d9f7b3baf571a8be;

extern ufcx_finite_element element_f9cce60a4987801757bdd2933f7b425e94134c99;

extern ufcx_finite_element element_5ccf54025616791d3881000d244751ef353a101e;

extern ufcx_finite_element element_61234b559574224db3ca164c52789af3076b011d;

extern ufcx_dofmap dofmap_635d4e60a5d12f84b092b035d9f7b3baf571a8be;

extern ufcx_dofmap dofmap_f9cce60a4987801757bdd2933f7b425e94134c99;

extern ufcx_dofmap dofmap_5ccf54025616791d3881000d244751ef353a101e;

extern ufcx_dofmap dofmap_61234b559574224db3ca164c52789af3076b011d;

extern ufcx_integral integral_5c99bdb50831b7fda9d9b84f0992906fae991e7b;

extern ufcx_integral integral_14bff921637ce9053bfb2a252efa8a231a167754;

extern ufcx_integral integral_87158cff0f4561a4b6860495d8e7e9e303679586;

extern ufcx_form form_8c096cd5f2740fbf79f0e0909ec43a93b7105f4b;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_d48eba6cd23ed46003514762ca6ec40467932970;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Order2_J(const char* function_name);

extern ufcx_form form_baec726439aead4e06cb7533e25bd6a9a75aff0d;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
