// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Hexa.py',
//                'MooneyRivlin_Hexa_Order2.py',
//                'MooneyRivlin_Tetra.py',
//                'MooneyRivlin_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_98ff221c153b48fb05d5b949bfcb968e89c14fe9;

extern ufcx_finite_element element_182d08db9ed72a05ecfe9f0e4c6e8459a80e7d2f;

extern ufcx_dofmap dofmap_98ff221c153b48fb05d5b949bfcb968e89c14fe9;

extern ufcx_dofmap dofmap_182d08db9ed72a05ecfe9f0e4c6e8459a80e7d2f;

extern ufcx_integral integral_18359925f2b1d7f2e2091cd6c696515912c271a8;

extern ufcx_integral integral_85c997c5cf086ac04ccd6424ac846f763e5caea6;

extern ufcx_integral integral_e2b741147d8b357a8133db2c67dd2d4fb41c6d57;

extern ufcx_form form_e1662bd3a0fef8ef6a3f78e5758d1ad7005ba9f3;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_F(const char* function_name);

extern ufcx_form form_dea70d02c235dc226187608f6b9f1d3ca50cfe28;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_J(const char* function_name);

extern ufcx_form form_030f935ce2e0074736de7b7df935119c33528b6f;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
