// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Hexa.py',
//                'MooneyRivlin_Hexa_Order2.py',
//                'MooneyRivlin_Tetra.py',
//                'MooneyRivlin_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_ea3b27c32b121e7fcfb645b92154baa26c6fe81c;

extern ufcx_finite_element element_ddcf1025be409233d1e0a8dda83d309bf86a9230;

extern ufcx_finite_element element_0cd10240fc95856b12763d499baf6ba8068fb0d0;

extern ufcx_finite_element element_d26dc267c872f6b2811f5f40463db98f75f4d854;

extern ufcx_dofmap dofmap_ea3b27c32b121e7fcfb645b92154baa26c6fe81c;

extern ufcx_dofmap dofmap_ddcf1025be409233d1e0a8dda83d309bf86a9230;

extern ufcx_dofmap dofmap_0cd10240fc95856b12763d499baf6ba8068fb0d0;

extern ufcx_dofmap dofmap_d26dc267c872f6b2811f5f40463db98f75f4d854;

extern ufcx_integral integral_0fafe646196aa0c0b0210057f13fff619c229745;

extern ufcx_integral integral_35102546ef807ef84568a07dbd28d9dc8930524d;

extern ufcx_integral integral_5f49b971f8422385a3c0dba56c7bbccb0a5fc3d0;

extern ufcx_form form_7c1c5bab7ee18d3f763ce104cda6f85bf689742e;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Order2_F(const char* function_name);

extern ufcx_form form_9f92d3eb8a703679e819096ed6b65bd0afc54542;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Order2_J(const char* function_name);

extern ufcx_form form_9aaf136efc4e9c50ebc24577ecefa9193033921e;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
