// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Hexa.py',
//                'MooneyRivlin_Hexa_Order2.py',
//                'MooneyRivlin_Tetra.py',
//                'MooneyRivlin_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_851993a1a04ebd20671aa60806dff3d96c6e4727;

extern ufcx_finite_element element_1baa2905edad7710023847d0a1ab15e12309a629;

extern ufcx_dofmap dofmap_851993a1a04ebd20671aa60806dff3d96c6e4727;

extern ufcx_dofmap dofmap_1baa2905edad7710023847d0a1ab15e12309a629;

extern ufcx_integral integral_bbde84098be1cba45ff5bc42d4e3e0e696cdddec;

extern ufcx_integral integral_093d70661414933f2753fd38faab67dc754b5414;

extern ufcx_integral integral_13b147247d3a8b82352808f549c83cabcf7b636a;

extern ufcx_form form_3107d0b603afb014c22811d820c509dbbc38eb0a;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_F(const char* function_name);

extern ufcx_form form_bb00c882143153ec58ea0a18d5828134ad9db224;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_J(const char* function_name);

extern ufcx_form form_470a386978eefb4943b5c2323342fd2286b6feb8;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
