// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_635d4e60a5d12f84b092b035d9f7b3baf571a8be;

extern ufcx_finite_element element_f9cce60a4987801757bdd2933f7b425e94134c99;

extern ufcx_finite_element element_5ccf54025616791d3881000d244751ef353a101e;

extern ufcx_finite_element element_61234b559574224db3ca164c52789af3076b011d;

extern ufcx_dofmap dofmap_635d4e60a5d12f84b092b035d9f7b3baf571a8be;

extern ufcx_dofmap dofmap_f9cce60a4987801757bdd2933f7b425e94134c99;

extern ufcx_dofmap dofmap_5ccf54025616791d3881000d244751ef353a101e;

extern ufcx_dofmap dofmap_61234b559574224db3ca164c52789af3076b011d;

extern ufcx_integral integral_9f21e77bb9258152033012c4ec1899dbb84dd68a;

extern ufcx_integral integral_e1eb98f7cf39396dba2c58d8144cd42cc1c26319;

extern ufcx_integral integral_cfbfcd577c504aed2e224f0165c0a97d6d807803;

extern ufcx_integral integral_b210e1e01162628dff099b0039fafae4265d947d;

extern ufcx_integral integral_c96586bb3d7905989ee2fdd4fb2002a638741909;

extern ufcx_form form_a17de94d820a25d112dbc81ee5f61abf21ded89b;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_5f690fb15761e13cc1607e2c231e95184948f54b;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Order2_J(const char* function_name);

extern ufcx_form form_61d6ecefe8bf95c4f9e9ee94296882218ecedb6f;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
