// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Tetra.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_98ff221c153b48fb05d5b949bfcb968e89c14fe9;

extern ufcx_finite_element element_182d08db9ed72a05ecfe9f0e4c6e8459a80e7d2f;

extern ufcx_dofmap dofmap_98ff221c153b48fb05d5b949bfcb968e89c14fe9;

extern ufcx_dofmap dofmap_182d08db9ed72a05ecfe9f0e4c6e8459a80e7d2f;

extern ufcx_integral integral_549e48b5abad7976615379301d6f711f113710d4;

extern ufcx_integral integral_46f1272d3f5b798119d7a2942d03abd5348d23e2;

extern ufcx_integral integral_8af0872be1b2f497bcffc8cfc48c9c97fbbf0afd;

extern ufcx_integral integral_3cebe37c43e73322f9f60d78016211447d216f84;

extern ufcx_integral integral_403a6a0c9a14d43f8ada6c096fa87b9d0c41d7d3;

extern ufcx_form form_aca25bb03fe633199380b2d19714ee1c61d441e9;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_F(const char* function_name);

extern ufcx_form form_9f868e3a46d3dd3f5b48f7661558ed27fb1b1a5b;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_J(const char* function_name);

extern ufcx_form form_75ff26285b763655fcbd5e1364e82b48db6ea224;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
