// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Hexa.py',
//                'MooneyRivlin_Hexa_Order2.py',
//                'MooneyRivlin_Tetra.py',
//                'MooneyRivlin_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_827e0731048b4eeeb15d8b84d7fc7208175924a4;

extern ufcx_finite_element element_6fd3c9ff1fb1dbc5751c582f00708d15637ca6f1;

extern ufcx_finite_element element_6a0881dbfb2bde0a242b4240501a9d5aaa7154a6;

extern ufcx_finite_element element_8fcbd9ae6633c6790d5e3c68f72323da1ff6d252;

extern ufcx_dofmap dofmap_827e0731048b4eeeb15d8b84d7fc7208175924a4;

extern ufcx_dofmap dofmap_6fd3c9ff1fb1dbc5751c582f00708d15637ca6f1;

extern ufcx_dofmap dofmap_6a0881dbfb2bde0a242b4240501a9d5aaa7154a6;

extern ufcx_dofmap dofmap_8fcbd9ae6633c6790d5e3c68f72323da1ff6d252;

extern ufcx_integral integral_a9473e5d5bff1e50b957f6e52f8929bf0c1b5968;

extern ufcx_integral integral_24d93365a25ff1eb79da90836671cf886fe34ec6;

extern ufcx_integral integral_91e06c3204b6d0981b02dbadd6f5e65afb2dfc7f;

extern ufcx_form form_31bd571bbd844101279a2b3f2c627e3c912b8ec6;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_ad7a6ac250df8cc703e532ae5a87803c837b4e35;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Order2_J(const char* function_name);

extern ufcx_form form_6dfb337e987f80e415556a675a8e6980480c7fff;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Tetra_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Tetra_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
