// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Hexa.py',
//                'MooneyRivlin_Hexa_Order2.py',
//                'MooneyRivlin_Tetra.py',
//                'MooneyRivlin_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_73d274b7350d0797db3175b18c11da45650d920e;

extern ufcx_finite_element element_490c823fd5b912383ac641974de257f513e58b54;

extern ufcx_finite_element element_b16cf72ba3d06c5e998bb8a0d689e785fc53d199;

extern ufcx_finite_element element_878594e5604a4307df33c36cd11e6164bfc9eeba;

extern ufcx_dofmap dofmap_73d274b7350d0797db3175b18c11da45650d920e;

extern ufcx_dofmap dofmap_490c823fd5b912383ac641974de257f513e58b54;

extern ufcx_dofmap dofmap_b16cf72ba3d06c5e998bb8a0d689e785fc53d199;

extern ufcx_dofmap dofmap_878594e5604a4307df33c36cd11e6164bfc9eeba;

extern ufcx_integral integral_a9e8c53ca5b5fbde23953450b6e5b1da980762bc;

extern ufcx_integral integral_09c480756157c0c455ff8169005d9f7d5410b9ed;

extern ufcx_integral integral_0069e27b22e76ef73cc085f3ec2cb9a9438d6689;

extern ufcx_form form_d1ae2b02fce92de8d7e3d24fd6f5e6346b64b315;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_F(const char* function_name);

extern ufcx_form form_3caf4dd09300753018371a0cbfe8e4049dcef1ea;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_J(const char* function_name);

extern ufcx_form form_f99a47bd93b047d2a50198c606b3e0f0a676f342;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
