// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Hexa.py',
//                'MooneyRivlin_Hexa_Order2.py',
//                'MooneyRivlin_Tetra.py',
//                'MooneyRivlin_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_9a8f8253e2ce3b0285ae648e6e421149bac8e316;

extern ufcx_finite_element element_e0603f46bc0d6f4cb2c9a9b00cac26c3a359e546;

extern ufcx_finite_element element_b6ab2acdf2e58dad768876dc7d1481381bb7197b;

extern ufcx_finite_element element_52431c8c0b179094cb83db4158892f74443a6c67;

extern ufcx_dofmap dofmap_9a8f8253e2ce3b0285ae648e6e421149bac8e316;

extern ufcx_dofmap dofmap_e0603f46bc0d6f4cb2c9a9b00cac26c3a359e546;

extern ufcx_dofmap dofmap_b6ab2acdf2e58dad768876dc7d1481381bb7197b;

extern ufcx_dofmap dofmap_52431c8c0b179094cb83db4158892f74443a6c67;

extern ufcx_integral integral_1b5821a2d91d26c6695bbedc2bf2e55e1e0069cd;

extern ufcx_integral integral_5c651c9590c3c82448d84111dbf7f56e11fbc544;

extern ufcx_integral integral_7fa5c4f3ccaf18f05802818325b3a2250897ecd7;

extern ufcx_form form_1368550656046f87a8c858d5fd562b167bcbc379;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Order2_F(const char* function_name);

extern ufcx_form form_457dce69b137fe1b6f7863159caa7bcef5787a29;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Order2_J(const char* function_name);

extern ufcx_form form_04c4a9a68138dbec3b11d45bf44800ea8809737b;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
