// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['MooneyRivlin_Hexa.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_1e6dd21838b5aed150f7a1df56fe135b84d2e70e;

extern ufcx_finite_element element_fa46853f91782f19b6f4c593f59dac7f0e916307;

extern ufcx_finite_element element_00e1a80bbdf056b4a6b4eb1b391c932e14a1ee65;

extern ufcx_finite_element element_0c4e046a76e54e3829221c3403f9b33c105e203b;

extern ufcx_dofmap dofmap_1e6dd21838b5aed150f7a1df56fe135b84d2e70e;

extern ufcx_dofmap dofmap_fa46853f91782f19b6f4c593f59dac7f0e916307;

extern ufcx_dofmap dofmap_00e1a80bbdf056b4a6b4eb1b391c932e14a1ee65;

extern ufcx_dofmap dofmap_0c4e046a76e54e3829221c3403f9b33c105e203b;

extern ufcx_integral integral_e03e0e1d5d0780796917ff968885953c7835d9ab;

extern ufcx_integral integral_d7a10964b47f7027af70c830a367cbe868a5bc9e;

extern ufcx_integral integral_7fa321b319eaaac48e0c10e5e92dc7e49e00c324;

extern ufcx_integral integral_70bf1fa386482936b57301d8a5260af76f48f162;

extern ufcx_integral integral_0bcaee68a2fe389fec53a3a0ed33447d2a0b1892;

extern ufcx_form form_95c7706d8a9447571ab3789833912c7debc2bc19;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_F(const char* function_name);

extern ufcx_form form_77eeaca65c862af474ffea2e7f6ef6bdbcc44c46;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_J(const char* function_name);

extern ufcx_form form_609e845c3524316007d0dffe3a549c060bb17b8f;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_MooneyRivlin_Hexa_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_MooneyRivlin_Hexa_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
