// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['NeoHooke_Tetra.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_fa87cee5c4927ef45d998ec9fec54bc2e34e5444;

extern ufcx_finite_element element_ac7b8695c5f1b030c221ce178a8ccf93e59b27a8;

extern ufcx_dofmap dofmap_fa87cee5c4927ef45d998ec9fec54bc2e34e5444;

extern ufcx_dofmap dofmap_ac7b8695c5f1b030c221ce178a8ccf93e59b27a8;

extern ufcx_integral integral_54d0ab5c0e70fd21cd170f6d953025bff266f434;

extern ufcx_integral integral_78b8f7c394e25f0a6f65179f5114bfe4f34e4d99;

extern ufcx_form form_4c655ec97e110b69def9071654dd92a2ccadff71;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Tetra_F(const char* function_name);

extern ufcx_form form_0afe5746943121928d06db3be55efbe7139a2ba8;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Tetra_J(const char* function_name);

#ifdef __cplusplus
}
#endif
