// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['NeoHooke_Hexa.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_d14a231e4d67edcd2877c5345f1c58a696674fd3;

extern ufcx_finite_element element_7b6627cb065a545ca48e688aac1924f5982e795c;

extern ufcx_dofmap dofmap_d14a231e4d67edcd2877c5345f1c58a696674fd3;

extern ufcx_dofmap dofmap_7b6627cb065a545ca48e688aac1924f5982e795c;

extern ufcx_integral integral_5ea950f37b4035eb264289e690afec99b55ff4c5;

extern ufcx_integral integral_38e95ccb06d7bb07db1022d64a5a37af28227092;

extern ufcx_form form_c9120994c92d4944ff493379fdcd48ee102b5d71;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_F(const char* function_name);

extern ufcx_form form_c99e9790ef8febe9803fd6e9d0761557663d5af3;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_J(const char* function_name);

#ifdef __cplusplus
}
#endif
