// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['NeoHooke_Tetra.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_939e348d61bf75197d6d65aa65302d4cecea1e54;

extern ufcx_finite_element element_4c3c9636ffe6a111ef45b55c2944fbcaa634d0ac;

extern ufcx_dofmap dofmap_939e348d61bf75197d6d65aa65302d4cecea1e54;

extern ufcx_dofmap dofmap_4c3c9636ffe6a111ef45b55c2944fbcaa634d0ac;

extern ufcx_integral integral_f0dcbd619ce8eac8ad7e271390b27b31b0614cf5;

extern ufcx_integral integral_5f213636e58260563befe6ccb589e2511da492de;

extern ufcx_form form_6563bebb851955c99ec60df01f1a5a0ac9ab63dd;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Tetra_F(const char* function_name);

extern ufcx_form form_ea3329bc4ffe365499b1f7adbdd8441a925d4392;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Tetra_J(const char* function_name);

#ifdef __cplusplus
}
#endif
