// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['NeoHooke_Hexa.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_86118b724a6f4963d18d1e9aedca5194c9568855;

extern ufcx_finite_element element_653f6e795941a62e750f98e700fe481d241493b4;

extern ufcx_finite_element element_eebedb153740b348cd1b59e8a9c2a9686b909ba6;

extern ufcx_finite_element element_e1766c5deec3e29c83f2b27eb7853b4f8e5179e8;

extern ufcx_dofmap dofmap_86118b724a6f4963d18d1e9aedca5194c9568855;

extern ufcx_dofmap dofmap_653f6e795941a62e750f98e700fe481d241493b4;

extern ufcx_dofmap dofmap_eebedb153740b348cd1b59e8a9c2a9686b909ba6;

extern ufcx_dofmap dofmap_e1766c5deec3e29c83f2b27eb7853b4f8e5179e8;

extern ufcx_integral integral_cd402d65b7ef0f63b02cb970fc096601cd8b19ae;

extern ufcx_integral integral_452de84e2345b48f321c014ffb2e457bdfc4d818;

extern ufcx_integral integral_3de515a706b4ed7a399866c9d907c092b677dd57;

extern ufcx_integral integral_07e2ac28e3483d30cef5ea41030d2883c4b70586;

extern ufcx_integral integral_c5207bb7676da9cf4f08865a69b93f8c5b1c601f;

extern ufcx_form form_18e2f43a31291c8d530d02ddd7e557d21084d552;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_F(const char* function_name);

extern ufcx_form form_9edae4f8a864066d4629bd20d246f1f156f925bb;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_J(const char* function_name);

extern ufcx_form form_1819fd96a91fc6c6f3b3cd77a2ca9e25f51c107a;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
