// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['NeoHooke_Hexa.py',
//                'NeoHooke_Hexa_Order2.py',
//                'NeoHooke_Tetra.py',
//                'NeoHooke_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_54aa707647b051d1f786ae1a9161d7c00e4009a6;

extern ufcx_finite_element element_f8c5c6f3e918c573fb7046556fd78e2c1541c875;

extern ufcx_finite_element element_0013537f9117dfbca9edcde0c7ba4a9caa4f8259;

extern ufcx_finite_element element_653ea89734408ff97174e919f717e6302d859d6b;

extern ufcx_dofmap dofmap_54aa707647b051d1f786ae1a9161d7c00e4009a6;

extern ufcx_dofmap dofmap_f8c5c6f3e918c573fb7046556fd78e2c1541c875;

extern ufcx_dofmap dofmap_0013537f9117dfbca9edcde0c7ba4a9caa4f8259;

extern ufcx_dofmap dofmap_653ea89734408ff97174e919f717e6302d859d6b;

extern ufcx_integral integral_5723acafe9c13fad5a19b1199d39a4f2d9155dcc;

extern ufcx_integral integral_9aa75c796a489a8823a72ab6e9ec5186bc139fde;

extern ufcx_integral integral_cd98eabf2c96f87932427d63823e61c9583e05a2;

extern ufcx_form form_b3c6554dc1b0d94956421dfd12f613dd572cfed0;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_Order2_F(const char* function_name);

extern ufcx_form form_74ef598e942c40336aacdb5f0d2eda92f6fad289;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_Order2_J(const char* function_name);

extern ufcx_form form_f27abebdc58a7a8fcc04ddf0c0b54bbc2b68bbe9;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
