// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['NeoHooke_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_17a97e123eef8d2a4963bce121e8eb3f44aa0c9a;

extern ufcx_finite_element element_6c55ec5c273be40a189b115d1f0c92f6c127e274;

extern ufcx_finite_element element_245f817e5f53640abdebf7310b7a715b0e8910a6;

extern ufcx_finite_element element_1fe49d7550e509ccee96a8f5d029606511c39b33;

extern ufcx_dofmap dofmap_17a97e123eef8d2a4963bce121e8eb3f44aa0c9a;

extern ufcx_dofmap dofmap_6c55ec5c273be40a189b115d1f0c92f6c127e274;

extern ufcx_dofmap dofmap_245f817e5f53640abdebf7310b7a715b0e8910a6;

extern ufcx_dofmap dofmap_1fe49d7550e509ccee96a8f5d029606511c39b33;

extern ufcx_integral integral_c35abcff9167c0670a9913558c5993c8127d4eee;

extern ufcx_integral integral_5a8255d2e0e5217db99068c7dd50e9ff6ccd1387;

extern ufcx_form form_cc0388f38af563ae0b0746bd6837d8491c6d2082;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_f658a45a7700c787458ebe483a8791740edec2b4;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Tetra_Order2_J(const char* function_name);

#ifdef __cplusplus
}
#endif
