// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['NeoHooke_Hexa.py',
//                'NeoHooke_Hexa_Order2.py',
//                'NeoHooke_Tetra.py',
//                'NeoHooke_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_86118b724a6f4963d18d1e9aedca5194c9568855;

extern ufcx_finite_element element_653f6e795941a62e750f98e700fe481d241493b4;

extern ufcx_finite_element element_eebedb153740b348cd1b59e8a9c2a9686b909ba6;

extern ufcx_finite_element element_e1766c5deec3e29c83f2b27eb7853b4f8e5179e8;

extern ufcx_dofmap dofmap_86118b724a6f4963d18d1e9aedca5194c9568855;

extern ufcx_dofmap dofmap_653f6e795941a62e750f98e700fe481d241493b4;

extern ufcx_dofmap dofmap_eebedb153740b348cd1b59e8a9c2a9686b909ba6;

extern ufcx_dofmap dofmap_e1766c5deec3e29c83f2b27eb7853b4f8e5179e8;

extern ufcx_integral integral_623c666990298532bf9ab6c26890d8b55519d743;

extern ufcx_integral integral_e2ca8b9deccd02bfde7418b91e1e20bca8b3660f;

extern ufcx_integral integral_b61e6334cebfca35307943f790118d0fe3994d41;

extern ufcx_form form_7d153dd7d0e436eddb130e2acdb32aca4a25a63c;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_F(const char* function_name);

extern ufcx_form form_56943c72e66ef3e6258ad433a7ea0082fc54c842;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_J(const char* function_name);

extern ufcx_form form_75d1d0b53b8de29a96d39dd8703c779bc1783059;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_NeoHooke_Hexa_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_NeoHooke_Hexa_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
