// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Hexa_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_476181db3ec5999d464d3fa1ccafeee06bc2f3e4;

extern ufcx_finite_element element_77e1d845144538d6ce284ccfc5a188a7670669d8;

extern ufcx_finite_element element_571c91305c1ec684e7709262b03f92e18d325b79;

extern ufcx_finite_element element_d0b2fd83c98f6aced53c633a1e772759ddb2e747;

extern ufcx_dofmap dofmap_476181db3ec5999d464d3fa1ccafeee06bc2f3e4;

extern ufcx_dofmap dofmap_77e1d845144538d6ce284ccfc5a188a7670669d8;

extern ufcx_dofmap dofmap_571c91305c1ec684e7709262b03f92e18d325b79;

extern ufcx_dofmap dofmap_d0b2fd83c98f6aced53c633a1e772759ddb2e747;

extern ufcx_integral integral_6b2dd9c6582ecea3e2086be44f4a9914e89ace10;

extern ufcx_integral integral_f90065fb13891028881828ef8abd5bce0a6ed1cf;

extern ufcx_integral integral_3214a5229dcf4afe0ee839a743e50d894bf29e38;

extern ufcx_integral integral_534408d7a281fef533bd1fa1f270b1dec265cf3a;

extern ufcx_integral integral_186cbb7eb858bef4394e9fe0a155159112793a4e;

extern ufcx_form form_da894143cd02e96a0788bd2b11aefe6b602cde2d;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_Order2_F(const char* function_name);

extern ufcx_form form_b16fcf8158096e89e5f3c9fb190945b9fe9969a0;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_Order2_J(const char* function_name);

extern ufcx_form form_a1482b4f0025aebbd560191fc08fd202c1e9c82c;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
