// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_6d46b51670d049475b6f32ef56c2ef5ba9aece12;

extern ufcx_finite_element element_bb16b20fa8c0ad894fe8afa8b763ac89c2d6c2c9;

extern ufcx_finite_element element_f62239856cf45573b24bff6bcdd1c0a12ddf43d2;

extern ufcx_finite_element element_3d9b69ecc287e119e05c3aab25fdffac67eb6a3d;

extern ufcx_dofmap dofmap_6d46b51670d049475b6f32ef56c2ef5ba9aece12;

extern ufcx_dofmap dofmap_bb16b20fa8c0ad894fe8afa8b763ac89c2d6c2c9;

extern ufcx_dofmap dofmap_f62239856cf45573b24bff6bcdd1c0a12ddf43d2;

extern ufcx_dofmap dofmap_3d9b69ecc287e119e05c3aab25fdffac67eb6a3d;

extern ufcx_integral integral_ab4dc9107cd4651d6e697084abaab8918c542aa4;

extern ufcx_integral integral_3ba4cf93b67118a70d2a3a867decb7e172d8ad2b;

extern ufcx_integral integral_a12e2634cff797eb5686969f883bb1f399868a3b;

extern ufcx_integral integral_6878b0812e43a66aacabdec522b383dc31d5d7b7;

extern ufcx_integral integral_8d2c306d4e37b10c1a792e725c1be0fa0a7a5b49;

extern ufcx_form form_6bcf0f5eab75da12ec092e906e8f66aa5f71345e;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_1410fc3da801032562fde326c215feb821712b89;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Order2_J(const char* function_name);

extern ufcx_form form_ea874aaad51425ce4922cdb0bc86c8f0f0538fca;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
