// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Hexa.py',
//                'Ogden_Hexa_Order2.py',
//                'Ogden_Tetra.py',
//                'Ogden_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_6d46b51670d049475b6f32ef56c2ef5ba9aece12;

extern ufcx_finite_element element_bb16b20fa8c0ad894fe8afa8b763ac89c2d6c2c9;

extern ufcx_finite_element element_f62239856cf45573b24bff6bcdd1c0a12ddf43d2;

extern ufcx_finite_element element_3d9b69ecc287e119e05c3aab25fdffac67eb6a3d;

extern ufcx_dofmap dofmap_6d46b51670d049475b6f32ef56c2ef5ba9aece12;

extern ufcx_dofmap dofmap_bb16b20fa8c0ad894fe8afa8b763ac89c2d6c2c9;

extern ufcx_dofmap dofmap_f62239856cf45573b24bff6bcdd1c0a12ddf43d2;

extern ufcx_dofmap dofmap_3d9b69ecc287e119e05c3aab25fdffac67eb6a3d;

extern ufcx_integral integral_befaccf91fa783a0fb10dc95e3a101d07531a532;

extern ufcx_integral integral_2861e8793b45c6a2fa79024bab0f0f4e2c28ba10;

extern ufcx_integral integral_dc06fa23ee9978f59ca8267c708143fa39472f96;

extern ufcx_form form_1aba15732aa4b061613e143ccf53f859daba48d6;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_5060cbbfe9c1748f4d72e074786f5e8f236e91ed;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Order2_J(const char* function_name);

extern ufcx_form form_29bd465ecd3503ba856db5f98f359d53573dc06e;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
