// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Hexa.py',
//                'Ogden_Hexa_Order2.py',
//                'Ogden_Tetra.py',
//                'Ogden_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_7723b55a58bd773bf52084899272f93cdad96888;

extern ufcx_finite_element element_00f743b88c1760eb5ed5a2352a3320edbc47ab2c;

extern ufcx_finite_element element_23e766f6c7a218fa1b16265bccebeba0f35c5e56;

extern ufcx_finite_element element_375c43b8f0c75b6a3979a5689d31797d71c49829;

extern ufcx_dofmap dofmap_7723b55a58bd773bf52084899272f93cdad96888;

extern ufcx_dofmap dofmap_00f743b88c1760eb5ed5a2352a3320edbc47ab2c;

extern ufcx_dofmap dofmap_23e766f6c7a218fa1b16265bccebeba0f35c5e56;

extern ufcx_dofmap dofmap_375c43b8f0c75b6a3979a5689d31797d71c49829;

extern ufcx_integral integral_ac4c1a58ef59aceff8fea69ebb2e2ffbf7489cae;

extern ufcx_integral integral_a831f4afdecdc991445b7b5bddcf01ded5afbf0c;

extern ufcx_form form_ef95aaa36f2ecf29563177165c88d08707973911;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_F(const char* function_name);

extern ufcx_form form_04329df232c6a39d4df6fdf6a4652f1eef4876b5;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_J(const char* function_name);

#ifdef __cplusplus
}
#endif
