// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Tetra.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_017ab768ddc77d252cf3674061d7d3aa1a6d94bc;

extern ufcx_finite_element element_e10eacc261c136e6e83ed1934ff2939078884840;

extern ufcx_dofmap dofmap_017ab768ddc77d252cf3674061d7d3aa1a6d94bc;

extern ufcx_dofmap dofmap_e10eacc261c136e6e83ed1934ff2939078884840;

extern ufcx_integral integral_8795790d9ac767c2faaa644dae8ad83ad80bb1b5;

extern ufcx_integral integral_c2ca8a162db7600afd7ff0f86fce2e4d8a3178c3;

extern ufcx_integral integral_98b185cbe5d165415b8027af370767eb686394f0;

extern ufcx_form form_1dd0428a67762215e4d0320d88290d006c0a43b0;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_F(const char* function_name);

extern ufcx_form form_2cb99835dcf90fcf6db74162716b38ede0606d58;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_J(const char* function_name);

extern ufcx_form form_d6db3ae68ec0a48f70f433f6d0bff1bfe6be5de0;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
