// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Hexa.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_ab1105e07ed213f5e0deb12c29c4391da43095f5;

extern ufcx_finite_element element_c736860d03cdcbe7df10e7a9b33eb640b5ba3d75;

extern ufcx_finite_element element_88104a5f80830c04674a42596f57c3a5e41e9f4d;

extern ufcx_finite_element element_883d0563752c0ad245f0cfab5fa7d07355b5b8d1;

extern ufcx_dofmap dofmap_ab1105e07ed213f5e0deb12c29c4391da43095f5;

extern ufcx_dofmap dofmap_c736860d03cdcbe7df10e7a9b33eb640b5ba3d75;

extern ufcx_dofmap dofmap_88104a5f80830c04674a42596f57c3a5e41e9f4d;

extern ufcx_dofmap dofmap_883d0563752c0ad245f0cfab5fa7d07355b5b8d1;

extern ufcx_integral integral_34e05468198c784d8c14808fcdbfe30bd08d167b;

extern ufcx_integral integral_73711261adbc53157f3f63600ed153b362a184a4;

extern ufcx_integral integral_836aa8e69fd2c238d99bb4a9b0a171a6b3a3852c;

extern ufcx_integral integral_e66072c370ee8d387b209e3a3aa236de3c91a1c3;

extern ufcx_integral integral_d63680ab9b2cd25777939b2659d48157fd952532;

extern ufcx_form form_3b4e0e7fedac86fd3e92c371cc338fc73315f0ef;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_F(const char* function_name);

extern ufcx_form form_86f63516e0880eb8847ae1db7cfff03c024d68d3;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_J(const char* function_name);

extern ufcx_form form_a33c7df5fc9e97b8d1e32c8c11cbbaf8b1734219;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
