// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Hexa.py',
//                'Ogden_Hexa_Order2.py',
//                'Ogden_Tetra.py',
//                'Ogden_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_e0a81737b98d749514ad6da48f61ab5b7255882a;

extern ufcx_finite_element element_4e233cf45d99d88a386409cf3370a7feceb55810;

extern ufcx_dofmap dofmap_e0a81737b98d749514ad6da48f61ab5b7255882a;

extern ufcx_dofmap dofmap_4e233cf45d99d88a386409cf3370a7feceb55810;

extern ufcx_integral integral_0db09e63bf5babdab781667f4df5ae1738c6cc78;

extern ufcx_integral integral_7920a13384aad61451d26edd29ab6f3f348a7cf8;

extern ufcx_form form_783e3b2d8651da246b458be3346ea5d8f4255ae0;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_F(const char* function_name);

extern ufcx_form form_f408bbdaa0136e3afa31965f32ab5244ba389a7b;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_J(const char* function_name);

#ifdef __cplusplus
}
#endif
