// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Hexa.py',
//                'Ogden_Hexa_Order2.py',
//                'Ogden_Tetra.py',
//                'Ogden_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_cd3b35e1c4ea6cf9620c74849cd524e834468174;

extern ufcx_finite_element element_4a11cf763137c8cde12828ef675efce8d20366c9;

extern ufcx_finite_element element_a7b1701270af0bb4c6ffcb98c9e3abaa7ce5898c;

extern ufcx_finite_element element_46df37bcd4af3ea025d4410d8db518d49649844f;

extern ufcx_dofmap dofmap_cd3b35e1c4ea6cf9620c74849cd524e834468174;

extern ufcx_dofmap dofmap_4a11cf763137c8cde12828ef675efce8d20366c9;

extern ufcx_dofmap dofmap_a7b1701270af0bb4c6ffcb98c9e3abaa7ce5898c;

extern ufcx_dofmap dofmap_46df37bcd4af3ea025d4410d8db518d49649844f;

extern ufcx_integral integral_fa471f8069068150fc00ca26d32a206fcb64c265;

extern ufcx_integral integral_f7b689fface816ca5c52727a634844f1773f65b2;

extern ufcx_form form_15d826a4a53cf2547df0dd7f124b1ba369dc7f8a;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_d0efa0cfb4baac8b53a2f119fbafd29ab183e86d;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Order2_J(const char* function_name);

#ifdef __cplusplus
}
#endif
