// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Hexa.py',
//                'Ogden_Hexa_Order2.py',
//                'Ogden_Tetra.py',
//                'Ogden_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_476181db3ec5999d464d3fa1ccafeee06bc2f3e4;

extern ufcx_finite_element element_77e1d845144538d6ce284ccfc5a188a7670669d8;

extern ufcx_finite_element element_571c91305c1ec684e7709262b03f92e18d325b79;

extern ufcx_finite_element element_d0b2fd83c98f6aced53c633a1e772759ddb2e747;

extern ufcx_dofmap dofmap_476181db3ec5999d464d3fa1ccafeee06bc2f3e4;

extern ufcx_dofmap dofmap_77e1d845144538d6ce284ccfc5a188a7670669d8;

extern ufcx_dofmap dofmap_571c91305c1ec684e7709262b03f92e18d325b79;

extern ufcx_dofmap dofmap_d0b2fd83c98f6aced53c633a1e772759ddb2e747;

extern ufcx_integral integral_04d122b1c3b97cd20a269cc32f9fd14fb17b0e39;

extern ufcx_integral integral_b4918a6135d7cfa6777ab5fb8a509987b1c152e9;

extern ufcx_integral integral_408864cbbf3d12533e76ea39154897824319a6a6;

extern ufcx_form form_096516eca1c77340ec98ada3917659cadbfee35d;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_Order2_F(const char* function_name);

extern ufcx_form form_5af4a445477681c18c95771823a9de9eb6180305;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_Order2_J(const char* function_name);

extern ufcx_form form_1800703a1c514f2b830cdb2756fd9d7c2f5a3425;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
