// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Hexa.py',
//                'Ogden_Hexa_Order2.py',
//                'Ogden_Tetra.py',
//                'Ogden_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_7f0741da81f50a3fbbbc97816762f93dddfa42c2;

extern ufcx_finite_element element_93583b64fb8791b1eac086c8322f4807172a6583;

extern ufcx_finite_element element_e5e09a33e654ed2caf2d65c3f5f821831bb3a6ab;

extern ufcx_finite_element element_d09c51b9c81f6a2ea66c0a4d541f1e5988377ed1;

extern ufcx_dofmap dofmap_7f0741da81f50a3fbbbc97816762f93dddfa42c2;

extern ufcx_dofmap dofmap_93583b64fb8791b1eac086c8322f4807172a6583;

extern ufcx_dofmap dofmap_e5e09a33e654ed2caf2d65c3f5f821831bb3a6ab;

extern ufcx_dofmap dofmap_d09c51b9c81f6a2ea66c0a4d541f1e5988377ed1;

extern ufcx_integral integral_0d55ba71a1805429ce707494319bb2db9c5b1c1a;

extern ufcx_integral integral_60b23af3ca22352b94d39027150c1ecc1e4e7964;

extern ufcx_form form_b9160ca429ab6f0e588b95dcba1a534999b81157;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_Order2_F(const char* function_name);

extern ufcx_form form_527573de29fd6efdafac52f8b898b9295c6a99e4;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Hexa_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Hexa_Order2_J(const char* function_name);

#ifdef __cplusplus
}
#endif
