// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Ogden_Tetra.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_017ab768ddc77d252cf3674061d7d3aa1a6d94bc;

extern ufcx_finite_element element_e10eacc261c136e6e83ed1934ff2939078884840;

extern ufcx_dofmap dofmap_017ab768ddc77d252cf3674061d7d3aa1a6d94bc;

extern ufcx_dofmap dofmap_e10eacc261c136e6e83ed1934ff2939078884840;

extern ufcx_integral integral_ea7ad60caa94ca62ce8aee6b742ac252ef7d91ee;

extern ufcx_integral integral_f348eab72f4180b3de640a9bba2e43126d508fd5;

extern ufcx_integral integral_d6ce0e0212340b0a9265460e4ecdc64ad71072bd;

extern ufcx_integral integral_acf796768f5576212a52377f9320dd00d87d71f3;

extern ufcx_integral integral_bf5b8fda9ff53ea9fd921f1bcaa32772dcadbb67;

extern ufcx_form form_869e5b087be0ba320d42402f21a9ce91dc215ded;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_F(const char* function_name);

extern ufcx_form form_d1a2339d9c86a8dbd92b6fb32855059c4cd61fce;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_J(const char* function_name);

extern ufcx_form form_72830cdaa728384fb840e6d397e3fbd8a263ac93;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Ogden_Tetra_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Ogden_Tetra_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
