// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Hexa.py',
//                'SaintVenantKirchhoff_Hexa_Order2.py',
//                'SaintVenantKirchhoff_Tetra.py',
//                'SaintVenantKirchhoff_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_f19ec6a3cf30b1196725fb845253bce17bdfb48f;

extern ufcx_finite_element element_49b6ba7218f9f526441b549725eec026a82b9f77;

extern ufcx_finite_element element_119a68fcd15ec88a83d4738ad0c462ee394c1941;

extern ufcx_finite_element element_d7d48a5d5278e8ec3dc7a0b3f220b601d788b79f;

extern ufcx_dofmap dofmap_f19ec6a3cf30b1196725fb845253bce17bdfb48f;

extern ufcx_dofmap dofmap_49b6ba7218f9f526441b549725eec026a82b9f77;

extern ufcx_dofmap dofmap_119a68fcd15ec88a83d4738ad0c462ee394c1941;

extern ufcx_dofmap dofmap_d7d48a5d5278e8ec3dc7a0b3f220b601d788b79f;

extern ufcx_integral integral_c01a5e075152324884b73e7978a22dab85d833a9;

extern ufcx_integral integral_7814c87b7075e86db1970d0e446e5cce65301940;

extern ufcx_integral integral_e54c3a27c23eff129bc0e328f79db9eabae13449;

extern ufcx_form form_8c98195e4f47705aeb75f6648cb0e32134b9fc3e;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_Order2_F(const char* function_name);

extern ufcx_form form_4b550cb2081f6a1bacbb0d35c558617b397112cd;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_Order2_J(const char* function_name);

extern ufcx_form form_2ef7b984fcc1ea691ec8af94404ad2cd0b6f88b2;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
