// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Hexa.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_1d1e6b8439316f6690a8a157716497c6aa3c2d10;

extern ufcx_finite_element element_61f3ee394cdc2cccd3896c4586cd1eb6dab6da1a;

extern ufcx_finite_element element_34b67ef59371eb1a4403cad402d4dec34918e3e7;

extern ufcx_finite_element element_c3a4936f914504ef5fd26d08ec365141968c068e;

extern ufcx_dofmap dofmap_1d1e6b8439316f6690a8a157716497c6aa3c2d10;

extern ufcx_dofmap dofmap_61f3ee394cdc2cccd3896c4586cd1eb6dab6da1a;

extern ufcx_dofmap dofmap_34b67ef59371eb1a4403cad402d4dec34918e3e7;

extern ufcx_dofmap dofmap_c3a4936f914504ef5fd26d08ec365141968c068e;

extern ufcx_integral integral_17654637d4a944d47aaee90c22cea6797933267c;

extern ufcx_integral integral_63b7ee8a91f9469c9c380a1fc7ef5bc88aae1b9b;

extern ufcx_integral integral_385c1f9eae82f08fd1e35b67a93a6bfb35c9908b;

extern ufcx_integral integral_a9f01d10a91f07e4f85c2de6a91dca5c91ebe8bb;

extern ufcx_integral integral_0f67a13b9a614c21075acd8d7f32d507a0690300;

extern ufcx_form form_159f9f5b5f0add65154ad96ca98a2da5f912bfa3;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_F(const char* function_name);

extern ufcx_form form_caaefcc9b7933681e7db21cbe0371e418a162309;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_J(const char* function_name);

extern ufcx_form form_741782df264a5a0a90e1e6f2f1c9e8ee11321fad;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
