// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Hexa.py',
//                'SaintVenantKirchhoff_Hexa_Order2.py',
//                'SaintVenantKirchhoff_Tetra.py',
//                'SaintVenantKirchhoff_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_1d1e6b8439316f6690a8a157716497c6aa3c2d10;

extern ufcx_finite_element element_61f3ee394cdc2cccd3896c4586cd1eb6dab6da1a;

extern ufcx_finite_element element_34b67ef59371eb1a4403cad402d4dec34918e3e7;

extern ufcx_finite_element element_c3a4936f914504ef5fd26d08ec365141968c068e;

extern ufcx_dofmap dofmap_1d1e6b8439316f6690a8a157716497c6aa3c2d10;

extern ufcx_dofmap dofmap_61f3ee394cdc2cccd3896c4586cd1eb6dab6da1a;

extern ufcx_dofmap dofmap_34b67ef59371eb1a4403cad402d4dec34918e3e7;

extern ufcx_dofmap dofmap_c3a4936f914504ef5fd26d08ec365141968c068e;

extern ufcx_integral integral_a657435b4a80d3581a1675847e876ff961663878;

extern ufcx_integral integral_52a2926a09baf7043c9bfc29137eab38daa7472c;

extern ufcx_integral integral_5264bc8512b21f23c9ac4a4273d9a901bc140a9f;

extern ufcx_form form_cb40e5103ca034d4798aae26eae2d65e9f7885a7;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_F(const char* function_name);

extern ufcx_form form_ee1c54b1aba5eaadce4f1ef423c92a069b7f2ff3;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_J(const char* function_name);

extern ufcx_form form_3e3098d5eb152fb834f1a945b7b140d7c21ecaca;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
