// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Tetra.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_a92f513b1616de4829f4f79421457f4228f459ce;

extern ufcx_finite_element element_6c100e5101e17dd663d7b5c8ac13c891c983d32c;

extern ufcx_dofmap dofmap_a92f513b1616de4829f4f79421457f4228f459ce;

extern ufcx_dofmap dofmap_6c100e5101e17dd663d7b5c8ac13c891c983d32c;

extern ufcx_integral integral_9b07be9fd5c0ca73208b6bc52750dcf6e72378b9;

extern ufcx_integral integral_b2fb8d6adf85fb8acc95c56bcd1156b56272e57c;

extern ufcx_integral integral_5ef3a46dd1eeb554ac641e4d555dd144de92d129;

extern ufcx_integral integral_290050653cf61963e1be4faa0e0f214a835394ff;

extern ufcx_integral integral_c1eb71a9f60d6c9a01dbfab641edac3720f94458;

extern ufcx_form form_ad141c75dc1210f7a7622cffac7868887951ddb2;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_F(const char* function_name);

extern ufcx_form form_bed10e752d326b4e03eccdc1d17d8549b44a22d2;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_J(const char* function_name);

extern ufcx_form form_38b0a39d008d1343cd4589229be03689ba26d3b1;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
