// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.4.3.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_c9a8b08313d96d9743ba3dd7ef3585c42f1e0a42;

extern ufcx_finite_element element_90220fdda24cbc26aeccbf3f9a638d1fb67f990a;

extern ufcx_finite_element element_a5dcb6b5c9ce01cf8b9d3143453dfe595d03d29a;

extern ufcx_finite_element element_379cfe039e21e19b57fb76182d064630a2dcd9a3;

extern ufcx_dofmap dofmap_c9a8b08313d96d9743ba3dd7ef3585c42f1e0a42;

extern ufcx_dofmap dofmap_90220fdda24cbc26aeccbf3f9a638d1fb67f990a;

extern ufcx_dofmap dofmap_a5dcb6b5c9ce01cf8b9d3143453dfe595d03d29a;

extern ufcx_dofmap dofmap_379cfe039e21e19b57fb76182d064630a2dcd9a3;

extern ufcx_integral integral_6bbfe6e7602eb4472e09e4c6b062b7e14e18953f;

extern ufcx_integral integral_e2467f3c32e7afc343d8cccff7ca0ea8846ab423;

extern ufcx_integral integral_05d79e18e714b29ee9e16bfcd8c60070936977a9;

extern ufcx_integral integral_9de652e70edc9560f8bf671bd807cc420acc7ce7;

extern ufcx_integral integral_e42dd3a1381d37aa338a4b7755a6e3cd108de240;

extern ufcx_form form_ba130b1ea6f116028be3e0c197b96f2e5e563b9f;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_f6d252b15552a70868c95e552354c11372ea05ff;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_Order2_J(const char* function_name);

extern ufcx_form form_b9c2266c80335d47194a7c8972182b17dd1d0be0;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_Order2_Pi;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_Order2_Pi(const char* function_name);

#ifdef __cplusplus
}
#endif
