// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Tetra_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_5af95d5b4da287d28b04ef32e2704aa12f125d4b;

extern ufcx_finite_element element_ea5ecc628fe20c7bebc5667e214e21e96bdea3d8;

extern ufcx_finite_element element_73188567f77a0998dd6b9b65a7527cc294ea3c3b;

extern ufcx_finite_element element_8570ec37749757ce3f4258f80c25969445a7de56;

extern ufcx_dofmap dofmap_5af95d5b4da287d28b04ef32e2704aa12f125d4b;

extern ufcx_dofmap dofmap_ea5ecc628fe20c7bebc5667e214e21e96bdea3d8;

extern ufcx_dofmap dofmap_73188567f77a0998dd6b9b65a7527cc294ea3c3b;

extern ufcx_dofmap dofmap_8570ec37749757ce3f4258f80c25969445a7de56;

extern ufcx_integral integral_6c180eaebbab90b114df921a9b382afbde53797c;

extern ufcx_integral integral_732cfaa41ccbe7f74ab61863c58ccbe00313b50b;

extern ufcx_form form_4c99ee2ee050b38757dcab4d0d9b0603cf4a45e7;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_70f59cad9f3f7aa88d356c56e270662dc8699336;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_Order2_J(const char* function_name);

#ifdef __cplusplus
}
#endif
