// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Hexa_Order2.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_f58ab3e4d2d888bccdbdaf92aa3ea229d6a42e8a;

extern ufcx_finite_element element_a1b485ad5ddf2dbf17fa94e2ddf274e58414432a;

extern ufcx_finite_element element_975b941e38bef61f1602304ba357d33ef4142bd8;

extern ufcx_finite_element element_3bce2c4fc0f55f0145ef075bfaaab27023a406ca;

extern ufcx_dofmap dofmap_f58ab3e4d2d888bccdbdaf92aa3ea229d6a42e8a;

extern ufcx_dofmap dofmap_a1b485ad5ddf2dbf17fa94e2ddf274e58414432a;

extern ufcx_dofmap dofmap_975b941e38bef61f1602304ba357d33ef4142bd8;

extern ufcx_dofmap dofmap_3bce2c4fc0f55f0145ef075bfaaab27023a406ca;

extern ufcx_integral integral_91d8c78dc330436542327d33c8afb15015d4989d;

extern ufcx_integral integral_e5c8b9cbba452d7569cd1a9c20d0ae69c391d377;

extern ufcx_form form_06085c87ed59245afe178be1f43609e24c824160;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_Order2_F(const char* function_name);

extern ufcx_form form_1e6b76bd4d62646886b35e5479790c77757f1665;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_Order2_J(const char* function_name);

#ifdef __cplusplus
}
#endif
