// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Tetra.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_0c86aaf55b684e1a3e1ffec43b7d412b0cdaa9f8;

extern ufcx_finite_element element_fdc35eb42643dc1e9633ac8e9bbbb5d2c8cdeb83;

extern ufcx_dofmap dofmap_0c86aaf55b684e1a3e1ffec43b7d412b0cdaa9f8;

extern ufcx_dofmap dofmap_fdc35eb42643dc1e9633ac8e9bbbb5d2c8cdeb83;

extern ufcx_integral integral_ef7baa73907651c78fe60c31e80da146dc042c33;

extern ufcx_integral integral_ef5d35f616ae5152f20a98febd6aca75335e6e81;

extern ufcx_form form_615a59b99643de47f34aa8dc09cd511fd87caab0;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_F(const char* function_name);

extern ufcx_form form_922163464e813344b55c9b00c0c0dc7686aec387;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_J(const char* function_name);

#ifdef __cplusplus
}
#endif
