// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '../../FEniCS_Generated_code/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Hexa.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_74ccf6e0dc12a972998bfc59fd80adbffe29ade3;

extern ufcx_finite_element element_71c1428ea3f31db04d84ad087545af02f593328e;

extern ufcx_finite_element element_ac62405838b534de369e2238c78143b580a63a8e;

extern ufcx_finite_element element_0505aba2807d483e35646e41e0f604583cb9bd89;

extern ufcx_dofmap dofmap_74ccf6e0dc12a972998bfc59fd80adbffe29ade3;

extern ufcx_dofmap dofmap_71c1428ea3f31db04d84ad087545af02f593328e;

extern ufcx_dofmap dofmap_ac62405838b534de369e2238c78143b580a63a8e;

extern ufcx_dofmap dofmap_0505aba2807d483e35646e41e0f604583cb9bd89;

extern ufcx_integral integral_18fc48753881e145623c4da8671de3729656c796;

extern ufcx_integral integral_70e971ede1a2660e594c85d32d96129cd03c884b;

extern ufcx_form form_c4a9999baf0b7432fd034f6c10f3ea140a5b4b7c;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_F(const char* function_name);

extern ufcx_form form_94c5c1768a2de499d386b770cfc059b27a670070;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_J(const char* function_name);

#ifdef __cplusplus
}
#endif
