#ifndef SOFAMESHLESS_BINDINGS_PYTHONEVENTBINDER_H
#define SOFAMESHLESS_BINDINGS_PYTHONEVENTBINDER_H

#include "SofaPython/PythonMacros.h"

SP_DECLARE_CLASS_TYPE(PythonEventBinder);


#endif //SOFAMESHLESS_BINDINGS_PYTHONEVENTBINDER_H
