// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Hexa.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_3b330276948921c1c6a6648a2ab577960075dc87;

extern ufcx_finite_element element_4ad9de4e238088845086fee1aec95348175abab9;

extern ufcx_dofmap dofmap_3b330276948921c1c6a6648a2ab577960075dc87;

extern ufcx_dofmap dofmap_4ad9de4e238088845086fee1aec95348175abab9;

extern ufcx_integral integral_fc41becdc4bd8cc0b792a40780ef86ee0fd8796c;

extern ufcx_integral integral_fe6e5768c76e2e39b785b3b79978273e0e1194a9;

extern ufcx_form form_a05c3638be934ca9cc54512cb9332a1bea310720;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_F(const char* function_name);

extern ufcx_form form_a1cd3f0a1b73fa3dcfdde4b98f2ea5851bc25dd1;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_J(const char* function_name);

#ifdef __cplusplus
}
#endif
