// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Tetra_Order2.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_55dc330e7511932c8110c9d58bbaa4d054122461;

extern ufcx_finite_element element_e54cd1227be415ed52e9dbacbce803294f2c270d;

extern ufcx_finite_element element_a7b0d5a6c2418757f545823466f8dd92228bf36f;

extern ufcx_finite_element element_8dc918ac2e3fabbbafadf5f5541395d4df05809b;

extern ufcx_dofmap dofmap_55dc330e7511932c8110c9d58bbaa4d054122461;

extern ufcx_dofmap dofmap_e54cd1227be415ed52e9dbacbce803294f2c270d;

extern ufcx_dofmap dofmap_a7b0d5a6c2418757f545823466f8dd92228bf36f;

extern ufcx_dofmap dofmap_8dc918ac2e3fabbbafadf5f5541395d4df05809b;

extern ufcx_integral integral_55657da7389b0b695ad69834fcaac5c854cea61e;

extern ufcx_integral integral_8bddfaa23ce94c3b6c4e5bd91662c7c61ee5a335;

extern ufcx_form form_d8b8025aa76beefb661396555808b444dac9ec42;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_Order2_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_Order2_F(const char* function_name);

extern ufcx_form form_6fca890bce338b9328db75860ca108ea6f938cf4;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_SaintVenantKirchhoff_Tetra_Order2_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_Order2_J(const char* function_name);

#ifdef __cplusplus
}
#endif
