#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.5.0.post0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'padlen': 1,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'verbosity': 30}


#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>

// Code for element element_d749a1f68b2636b5aec1120728ae05c3f6c8eb66






ufcx_finite_element element_d749a1f68b2636b5aec1120728ae05c3f6c8eb66 =
{
  .signature = "Basix element (P, tetrahedron, 1, gll_warped, unset, False)",
  .cell_shape = tetrahedron,
  .element_type = ufcx_basix_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 4,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 3,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_d749a1f68b2636b5aec1120728ae05c3f6c8eb66

// Code for element element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06

int value_shape_element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06[1] = { 3 };
int reference_value_shape_element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06[1] = { 3 };
ufcx_finite_element* sub_elements_element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06[3] = { &element_d749a1f68b2636b5aec1120728ae05c3f6c8eb66, &element_d749a1f68b2636b5aec1120728ae05c3f6c8eb66, &element_d749a1f68b2636b5aec1120728ae05c3f6c8eb66 };


ufcx_finite_element element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06 =
{
  .signature = "VectorElement(Basix element (P, tetrahedron, 1, gll_warped, unset, False), 3)",
  .cell_shape = tetrahedron,
  .element_type = ufcx_basix_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 12,
  .value_rank = 1,
  .value_shape = value_shape_element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
  .value_size = 3,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
  .reference_value_size = 3,
  .degree = 1,
  .block_size = 3,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 3,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 3,
  .sub_elements = sub_elements_element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
  .custom_element = NULL
};

// End of code for element element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06

// Code for element element_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3






ufcx_finite_element element_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3 =
{
  .signature = "Basix element (P, tetrahedron, 1, equispaced, unset, False)",
  .cell_shape = tetrahedron,
  .element_type = ufcx_basix_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 4,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 3,
  .discontinuous = false,
  .lagrange_variant = 0,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3

// Code for element element_db2bdbab9112f776c604a1d0c570269039160719

int value_shape_element_db2bdbab9112f776c604a1d0c570269039160719[1] = { 3 };
int reference_value_shape_element_db2bdbab9112f776c604a1d0c570269039160719[1] = { 3 };
ufcx_finite_element* sub_elements_element_db2bdbab9112f776c604a1d0c570269039160719[3] = { &element_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3, &element_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3, &element_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3 };


ufcx_finite_element element_db2bdbab9112f776c604a1d0c570269039160719 =
{
  .signature = "VectorElement(Basix element (P, tetrahedron, 1, equispaced, unset, False), 3)",
  .cell_shape = tetrahedron,
  .element_type = ufcx_basix_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 12,
  .value_rank = 1,
  .value_shape = value_shape_element_db2bdbab9112f776c604a1d0c570269039160719,
  .value_size = 3,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_db2bdbab9112f776c604a1d0c570269039160719,
  .reference_value_size = 3,
  .degree = 1,
  .block_size = 3,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 3,
  .discontinuous = false,
  .lagrange_variant = 0,
  .dpc_variant = -1,
  .num_sub_elements = 3,
  .sub_elements = sub_elements_element_db2bdbab9112f776c604a1d0c570269039160719,
  .custom_element = NULL
};

// End of code for element element_db2bdbab9112f776c604a1d0c570269039160719

// Code for dofmap dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66



void tabulate_entity_dofs_dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 2;
    dofs[1] = 3;
    break;
  case 1:
    dofs[0] = 1;
    dofs[1] = 3;
    break;
  case 2:
    dofs[0] = 1;
    dofs[1] = 2;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 3;
    break;
  case 4:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 5:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    dofs[2] = 3;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 3;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 3;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    break;
  }
  break;
case 3:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66[4] = { 1, 2, 3, 4 };

ufcx_dofmap dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66 =
{
  .signature = "FFCx dofmap for Basix element (P, tetrahedron, 1, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66

// Code for dofmap dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06

ufcx_dofmap* sub_dofmaps_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06[3] = { &dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66, &dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66, &dofmap_d749a1f68b2636b5aec1120728ae05c3f6c8eb66 };

void tabulate_entity_dofs_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 2;
    dofs[1] = 3;
    break;
  case 1:
    dofs[0] = 1;
    dofs[1] = 3;
    break;
  case 2:
    dofs[0] = 1;
    dofs[1] = 2;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 3;
    break;
  case 4:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 5:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    dofs[2] = 3;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 3;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 3;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    break;
  }
  break;
case 3:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06[4] = { 1, 2, 3, 4 };

ufcx_dofmap dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06 =
{
  .signature = "FFCx dofmap for VectorElement(Basix element (P, tetrahedron, 1, gll_warped, unset, False), 3)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 3,
  .num_entity_dofs = num_entity_dofs_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
  .num_sub_dofmaps = 3,
  .sub_dofmaps = sub_dofmaps_dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06
};

// End of code for dofmap dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06

// Code for dofmap dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3



void tabulate_entity_dofs_dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 2;
    dofs[1] = 3;
    break;
  case 1:
    dofs[0] = 1;
    dofs[1] = 3;
    break;
  case 2:
    dofs[0] = 1;
    dofs[1] = 2;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 3;
    break;
  case 4:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 5:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    dofs[2] = 3;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 3;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 3;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    break;
  }
  break;
case 3:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3[4] = { 1, 2, 3, 4 };

ufcx_dofmap dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3 =
{
  .signature = "FFCx dofmap for Basix element (P, tetrahedron, 1, equispaced, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3

// Code for dofmap dofmap_db2bdbab9112f776c604a1d0c570269039160719

ufcx_dofmap* sub_dofmaps_dofmap_db2bdbab9112f776c604a1d0c570269039160719[3] = { &dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3, &dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3, &dofmap_dad667686a78c6e3b2dbe9d57ca21d1cb68431a3 };

void tabulate_entity_dofs_dofmap_db2bdbab9112f776c604a1d0c570269039160719(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_db2bdbab9112f776c604a1d0c570269039160719(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 2;
    dofs[1] = 3;
    break;
  case 1:
    dofs[0] = 1;
    dofs[1] = 3;
    break;
  case 2:
    dofs[0] = 1;
    dofs[1] = 2;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 3;
    break;
  case 4:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 5:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    dofs[2] = 3;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 3;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 3;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    break;
  }
  break;
case 3:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_db2bdbab9112f776c604a1d0c570269039160719[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_db2bdbab9112f776c604a1d0c570269039160719[4] = { 1, 2, 3, 4 };

ufcx_dofmap dofmap_db2bdbab9112f776c604a1d0c570269039160719 =
{
  .signature = "FFCx dofmap for VectorElement(Basix element (P, tetrahedron, 1, equispaced, unset, False), 3)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 3,
  .num_entity_dofs = num_entity_dofs_dofmap_db2bdbab9112f776c604a1d0c570269039160719,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_db2bdbab9112f776c604a1d0c570269039160719,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_db2bdbab9112f776c604a1d0c570269039160719,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_db2bdbab9112f776c604a1d0c570269039160719,
  .num_sub_dofmaps = 3,
  .sub_dofmaps = sub_dofmaps_dofmap_db2bdbab9112f776c604a1d0c570269039160719
};

// End of code for dofmap dofmap_db2bdbab9112f776c604a1d0c570269039160719

// Code for integral integral_8aae8a7f0cf6672b5c4900cbdd52d6915ffea22c

void tabulate_tensor_integral_8aae8a7f0cf6672b5c4900cbdd52d6915ffea22c(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
  // Quadrature rules
  static const double weights_fad[4] = { 0.04166666666666666, 0.04166666666666666, 0.04166666666666666, 0.04166666666666666 };
  // Precomputed values of basis functions and precomputations
  // FE* dimensions: [permutation][entities][points][dofs]
  static const double FE21_C0_Qfad[1][1][4][4] =
    { { { { 0.1381966011250091, 0.5854101966249688, 0.138196601125011, 0.138196601125011 },
          { 0.1381966011250091, 0.138196601125011, 0.585410196624969, 0.138196601125011 },
          { 0.1381966011250091, 0.1381966011250109, 0.138196601125011, 0.585410196624969 },
          { 0.585410196624967, 0.1381966011250109, 0.138196601125011, 0.138196601125011 } } } };
  static const double FE21_C2_D100_Qfad[1][1][1][4] = { { { { -1.0, 1.0, 0.0, 0.0 } } } };
  static const double FE31_C0_D010_Qfad[1][1][1][4] = { { { { -1.0, 0.0, 1.0, 0.0 } } } };
  static const double FE31_C1_D001_Qfad[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
  // Quadrature loop independent computations for quadrature rule fad
  double w0_d100_c2 = 0.0;
  double J_c1 = 0.0;
  double J_c5 = 0.0;
  double J_c2 = 0.0;
  double J_c4 = 0.0;
  double J_c0 = 0.0;
  double J_c8 = 0.0;
  double J_c7 = 0.0;
  double J_c6 = 0.0;
  double J_c3 = 0.0;
  double w0_d010_c2 = 0.0;
  double w0_d001_c2 = 0.0;
  double w0_d100_c1 = 0.0;
  double w0_d010_c1 = 0.0;
  double w0_d001_c1 = 0.0;
  double w0_d100_c0 = 0.0;
  double w0_d010_c0 = 0.0;
  double w0_d001_c0 = 0.0;
  for (int ic = 0; ic < 4; ++ic)
  {
    w0_d100_c2 += w[ic * 3 + 2] * FE21_C2_D100_Qfad[0][0][0][ic];
    J_c1 += coordinate_dofs[ic * 3] * FE31_C0_D010_Qfad[0][0][0][ic];
    J_c5 += coordinate_dofs[ic * 3 + 1] * FE31_C1_D001_Qfad[0][0][0][ic];
    J_c2 += coordinate_dofs[ic * 3] * FE31_C1_D001_Qfad[0][0][0][ic];
    J_c4 += coordinate_dofs[ic * 3 + 1] * FE31_C0_D010_Qfad[0][0][0][ic];
    J_c0 += coordinate_dofs[ic * 3] * FE21_C2_D100_Qfad[0][0][0][ic];
    J_c8 += coordinate_dofs[ic * 3 + 2] * FE31_C1_D001_Qfad[0][0][0][ic];
    J_c7 += coordinate_dofs[ic * 3 + 2] * FE31_C0_D010_Qfad[0][0][0][ic];
    J_c6 += coordinate_dofs[ic * 3 + 2] * FE21_C2_D100_Qfad[0][0][0][ic];
    J_c3 += coordinate_dofs[ic * 3 + 1] * FE21_C2_D100_Qfad[0][0][0][ic];
    w0_d010_c2 += w[ic * 3 + 2] * FE31_C0_D010_Qfad[0][0][0][ic];
    w0_d001_c2 += w[ic * 3 + 2] * FE31_C1_D001_Qfad[0][0][0][ic];
    w0_d100_c1 += w[ic * 3 + 1] * FE21_C2_D100_Qfad[0][0][0][ic];
    w0_d010_c1 += w[ic * 3 + 1] * FE31_C0_D010_Qfad[0][0][0][ic];
    w0_d001_c1 += w[ic * 3 + 1] * FE31_C1_D001_Qfad[0][0][0][ic];
    w0_d100_c0 += w[ic * 3] * FE21_C2_D100_Qfad[0][0][0][ic];
    w0_d010_c0 += w[ic * 3] * FE31_C0_D010_Qfad[0][0][0][ic];
    w0_d001_c0 += w[ic * 3] * FE31_C1_D001_Qfad[0][0][0][ic];
  }
  double sp_fad[251];
  sp_fad[0] = J_c1 * J_c5;
  sp_fad[1] = J_c2 * J_c4;
  sp_fad[2] = sp_fad[0] + -1 * sp_fad[1];
  sp_fad[3] = J_c4 * J_c8;
  sp_fad[4] = J_c5 * J_c7;
  sp_fad[5] = sp_fad[3] + -1 * sp_fad[4];
  sp_fad[6] = J_c0 * sp_fad[5];
  sp_fad[7] = J_c5 * J_c6;
  sp_fad[8] = J_c3 * J_c8;
  sp_fad[9] = sp_fad[7] + -1 * sp_fad[8];
  sp_fad[10] = J_c1 * sp_fad[9];
  sp_fad[11] = sp_fad[6] + sp_fad[10];
  sp_fad[12] = J_c3 * J_c7;
  sp_fad[13] = J_c4 * J_c6;
  sp_fad[14] = sp_fad[12] + -1 * sp_fad[13];
  sp_fad[15] = J_c2 * sp_fad[14];
  sp_fad[16] = sp_fad[11] + sp_fad[15];
  sp_fad[17] = sp_fad[2] / sp_fad[16];
  sp_fad[18] = w0_d100_c2 * sp_fad[17];
  sp_fad[19] = J_c2 * J_c3;
  sp_fad[20] = J_c0 * J_c5;
  sp_fad[21] = sp_fad[19] + -1 * sp_fad[20];
  sp_fad[22] = sp_fad[21] / sp_fad[16];
  sp_fad[23] = w0_d010_c2 * sp_fad[22];
  sp_fad[24] = sp_fad[18] + sp_fad[23];
  sp_fad[25] = J_c0 * J_c4;
  sp_fad[26] = J_c1 * J_c3;
  sp_fad[27] = sp_fad[25] + -1 * sp_fad[26];
  sp_fad[28] = sp_fad[27] / sp_fad[16];
  sp_fad[29] = w0_d001_c2 * sp_fad[28];
  sp_fad[30] = sp_fad[24] + sp_fad[29];
  sp_fad[31] = J_c2 * J_c7;
  sp_fad[32] = J_c8 * (-1 * J_c1);
  sp_fad[33] = sp_fad[31] + sp_fad[32];
  sp_fad[34] = sp_fad[33] / sp_fad[16];
  sp_fad[35] = w0_d100_c1 * sp_fad[34];
  sp_fad[36] = J_c0 * J_c8;
  sp_fad[37] = J_c6 * (-1 * J_c2);
  sp_fad[38] = sp_fad[36] + sp_fad[37];
  sp_fad[39] = sp_fad[38] / sp_fad[16];
  sp_fad[40] = w0_d010_c1 * sp_fad[39];
  sp_fad[41] = sp_fad[35] + sp_fad[40];
  sp_fad[42] = J_c1 * J_c6;
  sp_fad[43] = J_c0 * J_c7;
  sp_fad[44] = sp_fad[42] + -1 * sp_fad[43];
  sp_fad[45] = sp_fad[44] / sp_fad[16];
  sp_fad[46] = w0_d001_c1 * sp_fad[45];
  sp_fad[47] = sp_fad[41] + sp_fad[46];
  sp_fad[48] = (1 + sp_fad[30]) * (1 + sp_fad[47]);
  sp_fad[49] = w0_d100_c1 * sp_fad[17];
  sp_fad[50] = w0_d010_c1 * sp_fad[22];
  sp_fad[51] = sp_fad[49] + sp_fad[50];
  sp_fad[52] = w0_d001_c1 * sp_fad[28];
  sp_fad[53] = sp_fad[51] + sp_fad[52];
  sp_fad[54] = w0_d100_c2 * sp_fad[34];
  sp_fad[55] = w0_d010_c2 * sp_fad[39];
  sp_fad[56] = sp_fad[54] + sp_fad[55];
  sp_fad[57] = w0_d001_c2 * sp_fad[45];
  sp_fad[58] = sp_fad[56] + sp_fad[57];
  sp_fad[59] = sp_fad[53] * sp_fad[58];
  sp_fad[60] = sp_fad[48] + -1 * sp_fad[59];
  sp_fad[61] = sp_fad[5] / sp_fad[16];
  sp_fad[62] = w0_d100_c0 * sp_fad[61];
  sp_fad[63] = J_c3 * (-1 * J_c8);
  sp_fad[64] = sp_fad[7] + sp_fad[63];
  sp_fad[65] = sp_fad[64] / sp_fad[16];
  sp_fad[66] = w0_d010_c0 * sp_fad[65];
  sp_fad[67] = sp_fad[62] + sp_fad[66];
  sp_fad[68] = sp_fad[14] / sp_fad[16];
  sp_fad[69] = w0_d001_c0 * sp_fad[68];
  sp_fad[70] = sp_fad[67] + sp_fad[69];
  sp_fad[71] = (1 + sp_fad[70]) * sp_fad[60];
  sp_fad[72] = w0_d100_c2 * sp_fad[61];
  sp_fad[73] = w0_d010_c2 * sp_fad[65];
  sp_fad[74] = sp_fad[72] + sp_fad[73];
  sp_fad[75] = w0_d001_c2 * sp_fad[68];
  sp_fad[76] = sp_fad[74] + sp_fad[75];
  sp_fad[77] = sp_fad[53] * sp_fad[76];
  sp_fad[78] = w0_d100_c1 * sp_fad[61];
  sp_fad[79] = w0_d010_c1 * sp_fad[65];
  sp_fad[80] = sp_fad[78] + sp_fad[79];
  sp_fad[81] = w0_d001_c1 * sp_fad[68];
  sp_fad[82] = sp_fad[80] + sp_fad[81];
  sp_fad[83] = (1 + sp_fad[30]) * sp_fad[82];
  sp_fad[84] = sp_fad[77] + -1 * sp_fad[83];
  sp_fad[85] = w0_d100_c0 * sp_fad[34];
  sp_fad[86] = w0_d010_c0 * sp_fad[39];
  sp_fad[87] = sp_fad[85] + sp_fad[86];
  sp_fad[88] = w0_d001_c0 * sp_fad[45];
  sp_fad[89] = sp_fad[87] + sp_fad[88];
  sp_fad[90] = sp_fad[84] * sp_fad[89];
  sp_fad[91] = sp_fad[71] + sp_fad[90];
  sp_fad[92] = sp_fad[82] * sp_fad[58];
  sp_fad[93] = (1 + sp_fad[47]) * sp_fad[76];
  sp_fad[94] = sp_fad[92] + -1 * sp_fad[93];
  sp_fad[95] = w0_d100_c0 * sp_fad[17];
  sp_fad[96] = w0_d010_c0 * sp_fad[22];
  sp_fad[97] = sp_fad[95] + sp_fad[96];
  sp_fad[98] = w0_d001_c0 * sp_fad[28];
  sp_fad[99] = sp_fad[97] + sp_fad[98];
  sp_fad[100] = sp_fad[94] * sp_fad[99];
  sp_fad[101] = sp_fad[91] + sp_fad[100];
  sp_fad[102] = sp_fad[60] / sp_fad[101];
  sp_fad[103] = c[6] * sp_fad[102];
  sp_fad[104] = (1 + sp_fad[70]) + (1 + sp_fad[70]);
  sp_fad[105] = sp_fad[104] * (c[6] / 2);
  sp_fad[106] = -1 * sp_fad[103] + sp_fad[105];
  sp_fad[107] = log(sp_fad[101]);
  sp_fad[108] = (2 * sp_fad[102]) * sp_fad[107];
  sp_fad[109] = sp_fad[108] * (c[7] / 2);
  sp_fad[110] = sp_fad[106] + sp_fad[109];
  sp_fad[111] = sp_fad[110] * sp_fad[61];
  sp_fad[112] = sp_fad[110] * sp_fad[65];
  sp_fad[113] = sp_fad[110] * sp_fad[68];
  sp_fad[114] = sp_fad[99] * sp_fad[58];
  sp_fad[115] = sp_fad[89] * (-1 * (1 + sp_fad[30]));
  sp_fad[116] = sp_fad[114] + sp_fad[115];
  sp_fad[117] = sp_fad[116] / sp_fad[101];
  sp_fad[118] = c[6] * sp_fad[117];
  sp_fad[119] = sp_fad[82] + sp_fad[82];
  sp_fad[120] = sp_fad[119] * (c[6] / 2);
  sp_fad[121] = -1 * sp_fad[118] + sp_fad[120];
  sp_fad[122] = (2 * sp_fad[117]) * sp_fad[107];
  sp_fad[123] = sp_fad[122] * (c[7] / 2);
  sp_fad[124] = sp_fad[121] + sp_fad[123];
  sp_fad[125] = sp_fad[124] * sp_fad[61];
  sp_fad[126] = sp_fad[124] * sp_fad[65];
  sp_fad[127] = sp_fad[124] * sp_fad[68];
  sp_fad[128] = sp_fad[53] * sp_fad[89];
  sp_fad[129] = sp_fad[99] * (-1 * (1 + sp_fad[47]));
  sp_fad[130] = sp_fad[128] + sp_fad[129];
  sp_fad[131] = sp_fad[130] / sp_fad[101];
  sp_fad[132] = c[6] * sp_fad[131];
  sp_fad[133] = sp_fad[76] + sp_fad[76];
  sp_fad[134] = sp_fad[133] * (c[6] / 2);
  sp_fad[135] = -1 * sp_fad[132] + sp_fad[134];
  sp_fad[136] = (2 * sp_fad[131]) * sp_fad[107];
  sp_fad[137] = sp_fad[136] * (c[7] / 2);
  sp_fad[138] = sp_fad[135] + sp_fad[137];
  sp_fad[139] = sp_fad[138] * sp_fad[61];
  sp_fad[140] = sp_fad[138] * sp_fad[65];
  sp_fad[141] = sp_fad[138] * sp_fad[68];
  sp_fad[142] = sp_fad[84] / sp_fad[101];
  sp_fad[143] = c[6] * sp_fad[142];
  sp_fad[144] = sp_fad[89] + sp_fad[89];
  sp_fad[145] = sp_fad[144] * (c[6] / 2);
  sp_fad[146] = -1 * sp_fad[143] + sp_fad[145];
  sp_fad[147] = (2 * sp_fad[142]) * sp_fad[107];
  sp_fad[148] = sp_fad[147] * (c[7] / 2);
  sp_fad[149] = sp_fad[146] + sp_fad[148];
  sp_fad[150] = sp_fad[149] * sp_fad[34];
  sp_fad[151] = sp_fad[149] * sp_fad[39];
  sp_fad[152] = sp_fad[149] * sp_fad[45];
  sp_fad[153] = (1 + sp_fad[30]) * (1 + sp_fad[70]);
  sp_fad[154] = sp_fad[99] * (-1 * sp_fad[76]);
  sp_fad[155] = sp_fad[153] + sp_fad[154];
  sp_fad[156] = sp_fad[155] / sp_fad[101];
  sp_fad[157] = c[6] * sp_fad[156];
  sp_fad[158] = (1 + sp_fad[47]) + (1 + sp_fad[47]);
  sp_fad[159] = sp_fad[158] * (c[6] / 2);
  sp_fad[160] = -1 * sp_fad[157] + sp_fad[159];
  sp_fad[161] = (2 * sp_fad[156]) * sp_fad[107];
  sp_fad[162] = sp_fad[161] * (c[7] / 2);
  sp_fad[163] = sp_fad[160] + sp_fad[162];
  sp_fad[164] = sp_fad[163] * sp_fad[34];
  sp_fad[165] = sp_fad[163] * sp_fad[39];
  sp_fad[166] = sp_fad[163] * sp_fad[45];
  sp_fad[167] = sp_fad[99] * sp_fad[82];
  sp_fad[168] = (1 + sp_fad[70]) * (-1 * sp_fad[53]);
  sp_fad[169] = sp_fad[167] + sp_fad[168];
  sp_fad[170] = sp_fad[169] / sp_fad[101];
  sp_fad[171] = c[6] * sp_fad[170];
  sp_fad[172] = sp_fad[58] + sp_fad[58];
  sp_fad[173] = sp_fad[172] * (c[6] / 2);
  sp_fad[174] = -1 * sp_fad[171] + sp_fad[173];
  sp_fad[175] = (2 * sp_fad[170]) * sp_fad[107];
  sp_fad[176] = sp_fad[175] * (c[7] / 2);
  sp_fad[177] = sp_fad[174] + sp_fad[176];
  sp_fad[178] = sp_fad[177] * sp_fad[34];
  sp_fad[179] = sp_fad[177] * sp_fad[39];
  sp_fad[180] = sp_fad[177] * sp_fad[45];
  sp_fad[181] = sp_fad[150] + sp_fad[111];
  sp_fad[182] = sp_fad[151] + sp_fad[112];
  sp_fad[183] = sp_fad[113] + sp_fad[152];
  sp_fad[184] = sp_fad[164] + sp_fad[125];
  sp_fad[185] = sp_fad[165] + sp_fad[126];
  sp_fad[186] = sp_fad[127] + sp_fad[166];
  sp_fad[187] = sp_fad[178] + sp_fad[139];
  sp_fad[188] = sp_fad[179] + sp_fad[140];
  sp_fad[189] = sp_fad[141] + sp_fad[180];
  sp_fad[190] = sp_fad[94] / sp_fad[101];
  sp_fad[191] = c[6] * sp_fad[190];
  sp_fad[192] = sp_fad[99] + sp_fad[99];
  sp_fad[193] = sp_fad[192] * (c[6] / 2);
  sp_fad[194] = -1 * sp_fad[191] + sp_fad[193];
  sp_fad[195] = (2 * sp_fad[190]) * sp_fad[107];
  sp_fad[196] = sp_fad[195] * (c[7] / 2);
  sp_fad[197] = sp_fad[194] + sp_fad[196];
  sp_fad[198] = sp_fad[197] * sp_fad[17];
  sp_fad[199] = sp_fad[197] * sp_fad[22];
  sp_fad[200] = sp_fad[197] * sp_fad[28];
  sp_fad[201] = sp_fad[76] * sp_fad[89];
  sp_fad[202] = (1 + sp_fad[70]) * (-1 * sp_fad[58]);
  sp_fad[203] = sp_fad[201] + sp_fad[202];
  sp_fad[204] = sp_fad[203] / sp_fad[101];
  sp_fad[205] = c[6] * sp_fad[204];
  sp_fad[206] = sp_fad[53] + sp_fad[53];
  sp_fad[207] = sp_fad[206] * (c[6] / 2);
  sp_fad[208] = -1 * sp_fad[205] + sp_fad[207];
  sp_fad[209] = (2 * sp_fad[204]) * sp_fad[107];
  sp_fad[210] = sp_fad[209] * (c[7] / 2);
  sp_fad[211] = sp_fad[208] + sp_fad[210];
  sp_fad[212] = sp_fad[211] * sp_fad[17];
  sp_fad[213] = sp_fad[211] * sp_fad[22];
  sp_fad[214] = sp_fad[211] * sp_fad[28];
  sp_fad[215] = (1 + sp_fad[70]) * (1 + sp_fad[47]);
  sp_fad[216] = sp_fad[89] * (-1 * sp_fad[82]);
  sp_fad[217] = sp_fad[215] + sp_fad[216];
  sp_fad[218] = sp_fad[217] / sp_fad[101];
  sp_fad[219] = c[6] * sp_fad[218];
  sp_fad[220] = (1 + sp_fad[30]) + (1 + sp_fad[30]);
  sp_fad[221] = sp_fad[220] * (c[6] / 2);
  sp_fad[222] = -1 * sp_fad[219] + sp_fad[221];
  sp_fad[223] = (2 * sp_fad[218]) * sp_fad[107];
  sp_fad[224] = sp_fad[223] * (c[7] / 2);
  sp_fad[225] = sp_fad[222] + sp_fad[224];
  sp_fad[226] = sp_fad[225] * sp_fad[17];
  sp_fad[227] = sp_fad[225] * sp_fad[22];
  sp_fad[228] = sp_fad[225] * sp_fad[28];
  sp_fad[229] = sp_fad[181] + sp_fad[198];
  sp_fad[230] = sp_fad[182] + sp_fad[199];
  sp_fad[231] = sp_fad[183] + sp_fad[200];
  sp_fad[232] = sp_fad[184] + sp_fad[212];
  sp_fad[233] = sp_fad[185] + sp_fad[213];
  sp_fad[234] = sp_fad[186] + sp_fad[214];
  sp_fad[235] = sp_fad[187] + sp_fad[226];
  sp_fad[236] = sp_fad[188] + sp_fad[227];
  sp_fad[237] = sp_fad[189] + sp_fad[228];
  sp_fad[238] = fabs(sp_fad[16]);
  sp_fad[239] = sp_fad[229] * sp_fad[238];
  sp_fad[240] = sp_fad[230] * sp_fad[238];
  sp_fad[241] = sp_fad[231] * sp_fad[238];
  sp_fad[242] = sp_fad[232] * sp_fad[238];
  sp_fad[243] = sp_fad[233] * sp_fad[238];
  sp_fad[244] = sp_fad[234] * sp_fad[238];
  sp_fad[245] = sp_fad[235] * sp_fad[238];
  sp_fad[246] = sp_fad[236] * sp_fad[238];
  sp_fad[247] = sp_fad[237] * sp_fad[238];
  sp_fad[248] = (-1 * c[0]) * sp_fad[238];
  sp_fad[249] = (-1 * c[1]) * sp_fad[238];
  sp_fad[250] = (-1 * c[2]) * sp_fad[238];
  for (int iq = 0; iq < 4; ++iq)
  {
    const double fw0 = sp_fad[248] * weights_fad[iq];
    const double fw1 = sp_fad[239] * weights_fad[iq];
    const double fw2 = sp_fad[240] * weights_fad[iq];
    const double fw3 = sp_fad[241] * weights_fad[iq];
    const double fw4 = sp_fad[249] * weights_fad[iq];
    const double fw5 = sp_fad[242] * weights_fad[iq];
    const double fw6 = sp_fad[243] * weights_fad[iq];
    const double fw7 = sp_fad[244] * weights_fad[iq];
    const double fw8 = sp_fad[250] * weights_fad[iq];
    const double fw9 = sp_fad[245] * weights_fad[iq];
    const double fw10 = sp_fad[246] * weights_fad[iq];
    const double fw11 = sp_fad[247] * weights_fad[iq];
    for (int i = 0; i < 4; ++i)
    {
      A[3 * i] += fw0 * FE21_C0_Qfad[0][0][iq][i] + fw1 * FE21_C2_D100_Qfad[0][0][0][i] + fw2 * FE31_C0_D010_Qfad[0][0][0][i] + fw3 * FE31_C1_D001_Qfad[0][0][0][i];
      A[3 * i + 1] += fw4 * FE21_C0_Qfad[0][0][iq][i] + fw5 * FE21_C2_D100_Qfad[0][0][0][i] + fw6 * FE31_C0_D010_Qfad[0][0][0][i] + fw7 * FE31_C1_D001_Qfad[0][0][0][i];
      A[3 * i + 2] += fw8 * FE21_C0_Qfad[0][0][iq][i] + fw9 * FE21_C2_D100_Qfad[0][0][0][i] + fw10 * FE31_C0_D010_Qfad[0][0][0][i] + fw11 * FE31_C1_D001_Qfad[0][0][0][i];
    }
  }
}

bool enabled_coefficients_integral_8aae8a7f0cf6672b5c4900cbdd52d6915ffea22c[1] = { false };

ufcx_integral integral_8aae8a7f0cf6672b5c4900cbdd52d6915ffea22c =
{
  .enabled_coefficients = enabled_coefficients_integral_8aae8a7f0cf6672b5c4900cbdd52d6915ffea22c,
  .tabulate_tensor_float64 = tabulate_tensor_integral_8aae8a7f0cf6672b5c4900cbdd52d6915ffea22c,
  .needs_facet_permutations = false,
  .coordinate_element = &element_db2bdbab9112f776c604a1d0c570269039160719,
};

// End of code for integral integral_8aae8a7f0cf6672b5c4900cbdd52d6915ffea22c

// Code for integral integral_28e5cd7552f11de88d809fba849192ceb3e1c18e

void tabulate_tensor_integral_28e5cd7552f11de88d809fba849192ceb3e1c18e(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
  // Quadrature rules
  static const double weights_48e[3] = { 0.1666666666666667, 0.1666666666666667, 0.1666666666666667 };
  // Precomputed values of basis functions and precomputations
  // FE* dimensions: [permutation][entities][points][dofs]
  static const double FE13_C1_D001_F_Q48e[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
  static const double FE13_C1_D010_F_Q48e[1][1][1][4] = { { { { -1.0, 0.0, 1.0, 0.0 } } } };
  static const double FE13_C1_D100_F_Q48e[1][1][1][4] = { { { { -1.0, 1.0, 0.0, 0.0 } } } };
  static const double FE3_C0_F_Q48e[1][4][3][4] =
    { { { { 0.0, 0.6666666666666667, 0.1666666666666667, 0.1666666666666666 },
          { 0.0, 0.1666666666666667, 0.1666666666666667, 0.6666666666666667 },
          { 0.0, 0.1666666666666668, 0.6666666666666667, 0.1666666666666666 } },
        { { 0.6666666666666667, 0.0, 0.1666666666666667, 0.1666666666666666 },
          { 0.1666666666666667, 0.0, 0.1666666666666667, 0.6666666666666667 },
          { 0.1666666666666668, 0.0, 0.6666666666666667, 0.1666666666666666 } },
        { { 0.6666666666666666, 0.1666666666666667, 0.0, 0.1666666666666666 },
          { 0.1666666666666667, 0.1666666666666667, 0.0, 0.6666666666666667 },
          { 0.1666666666666667, 0.6666666666666665, 0.0, 0.1666666666666666 } },
        { { 0.6666666666666666, 0.1666666666666667, 0.1666666666666667, 0.0 },
          { 0.1666666666666667, 0.1666666666666667, 0.6666666666666667, 0.0 },
          { 0.1666666666666667, 0.6666666666666666, 0.1666666666666667, 0.0 } } } };
  static const double tetrahedron_reference_facet_jacobian[4][3][2] =
    { { { -1.0, -1.0 },
        { 1.0, 0.0 },
        { 0.0, 1.0 } },
      { { 0.0, 0.0 },
        { 1.0, 0.0 },
        { 0.0, 1.0 } },
      { { 1.0, 0.0 },
        { 0.0, 0.0 },
        { 0.0, 1.0 } },
      { { 1.0, 0.0 },
        { 0.0, 1.0 },
        { 0.0, 0.0 } } };
  // Quadrature loop independent computations for quadrature rule 48e
  double J_c3 = 0.0;
  double J_c4 = 0.0;
  double J_c5 = 0.0;
  double J_c6 = 0.0;
  double J_c7 = 0.0;
  double J_c8 = 0.0;
  double J_c0 = 0.0;
  double J_c1 = 0.0;
  double J_c2 = 0.0;
  for (int ic = 0; ic < 4; ++ic)
  {
    J_c3 += coordinate_dofs[ic * 3 + 1] * FE13_C1_D100_F_Q48e[0][0][0][ic];
    J_c4 += coordinate_dofs[ic * 3 + 1] * FE13_C1_D010_F_Q48e[0][0][0][ic];
    J_c5 += coordinate_dofs[ic * 3 + 1] * FE13_C1_D001_F_Q48e[0][0][0][ic];
    J_c6 += coordinate_dofs[ic * 3 + 2] * FE13_C1_D100_F_Q48e[0][0][0][ic];
    J_c7 += coordinate_dofs[ic * 3 + 2] * FE13_C1_D010_F_Q48e[0][0][0][ic];
    J_c8 += coordinate_dofs[ic * 3 + 2] * FE13_C1_D001_F_Q48e[0][0][0][ic];
    J_c0 += coordinate_dofs[ic * 3] * FE13_C1_D100_F_Q48e[0][0][0][ic];
    J_c1 += coordinate_dofs[ic * 3] * FE13_C1_D010_F_Q48e[0][0][0][ic];
    J_c2 += coordinate_dofs[ic * 3] * FE13_C1_D001_F_Q48e[0][0][0][ic];
  }
  double sp_48e[48];
  sp_48e[0] = tetrahedron_reference_facet_jacobian[entity_local_index[0]][0][0] * J_c3;
  sp_48e[1] = tetrahedron_reference_facet_jacobian[entity_local_index[0]][1][0] * J_c4;
  sp_48e[2] = sp_48e[0] + sp_48e[1];
  sp_48e[3] = J_c5 * tetrahedron_reference_facet_jacobian[entity_local_index[0]][2][0];
  sp_48e[4] = sp_48e[2] + sp_48e[3];
  sp_48e[5] = tetrahedron_reference_facet_jacobian[entity_local_index[0]][0][1] * J_c6;
  sp_48e[6] = tetrahedron_reference_facet_jacobian[entity_local_index[0]][1][1] * J_c7;
  sp_48e[7] = sp_48e[5] + sp_48e[6];
  sp_48e[8] = tetrahedron_reference_facet_jacobian[entity_local_index[0]][2][1] * J_c8;
  sp_48e[9] = sp_48e[7] + sp_48e[8];
  sp_48e[10] = sp_48e[4] * sp_48e[9];
  sp_48e[11] = tetrahedron_reference_facet_jacobian[entity_local_index[0]][0][1] * J_c3;
  sp_48e[12] = J_c4 * tetrahedron_reference_facet_jacobian[entity_local_index[0]][1][1];
  sp_48e[13] = sp_48e[11] + sp_48e[12];
  sp_48e[14] = J_c5 * tetrahedron_reference_facet_jacobian[entity_local_index[0]][2][1];
  sp_48e[15] = sp_48e[13] + sp_48e[14];
  sp_48e[16] = tetrahedron_reference_facet_jacobian[entity_local_index[0]][0][0] * J_c6;
  sp_48e[17] = tetrahedron_reference_facet_jacobian[entity_local_index[0]][1][0] * J_c7;
  sp_48e[18] = sp_48e[16] + sp_48e[17];
  sp_48e[19] = tetrahedron_reference_facet_jacobian[entity_local_index[0]][2][0] * J_c8;
  sp_48e[20] = sp_48e[18] + sp_48e[19];
  sp_48e[21] = sp_48e[15] * sp_48e[20];
  sp_48e[22] = sp_48e[10] + -1 * sp_48e[21];
  sp_48e[23] = sp_48e[22] * sp_48e[22];
  sp_48e[24] = J_c0 * tetrahedron_reference_facet_jacobian[entity_local_index[0]][0][1];
  sp_48e[25] = J_c1 * tetrahedron_reference_facet_jacobian[entity_local_index[0]][1][1];
  sp_48e[26] = sp_48e[24] + sp_48e[25];
  sp_48e[27] = J_c2 * tetrahedron_reference_facet_jacobian[entity_local_index[0]][2][1];
  sp_48e[28] = sp_48e[26] + sp_48e[27];
  sp_48e[29] = sp_48e[28] * sp_48e[20];
  sp_48e[30] = J_c0 * tetrahedron_reference_facet_jacobian[entity_local_index[0]][0][0];
  sp_48e[31] = J_c1 * tetrahedron_reference_facet_jacobian[entity_local_index[0]][1][0];
  sp_48e[32] = sp_48e[30] + sp_48e[31];
  sp_48e[33] = J_c2 * tetrahedron_reference_facet_jacobian[entity_local_index[0]][2][0];
  sp_48e[34] = sp_48e[32] + sp_48e[33];
  sp_48e[35] = sp_48e[34] * sp_48e[9];
  sp_48e[36] = sp_48e[29] + -1 * sp_48e[35];
  sp_48e[37] = sp_48e[36] * sp_48e[36];
  sp_48e[38] = sp_48e[23] + sp_48e[37];
  sp_48e[39] = sp_48e[34] * sp_48e[15];
  sp_48e[40] = sp_48e[4] * sp_48e[28];
  sp_48e[41] = sp_48e[39] + -1 * sp_48e[40];
  sp_48e[42] = sp_48e[41] * sp_48e[41];
  sp_48e[43] = sp_48e[38] + sp_48e[42];
  sp_48e[44] = sqrt(sp_48e[43]);
  sp_48e[45] = (-1 * c[3]) * sp_48e[44];
  sp_48e[46] = (-1 * c[4]) * sp_48e[44];
  sp_48e[47] = (-1 * c[5]) * sp_48e[44];
  for (int iq = 0; iq < 3; ++iq)
  {
    const double fw0 = sp_48e[45] * weights_48e[iq];
    const double fw1 = sp_48e[46] * weights_48e[iq];
    const double fw2 = sp_48e[47] * weights_48e[iq];
    for (int i = 0; i < 4; ++i)
    {
      A[3 * i] += fw0 * FE3_C0_F_Q48e[0][entity_local_index[0]][iq][i];
      A[3 * i + 1] += fw1 * FE3_C0_F_Q48e[0][entity_local_index[0]][iq][i];
      A[3 * i + 2] += fw2 * FE3_C0_F_Q48e[0][entity_local_index[0]][iq][i];
    }
  }
}

bool enabled_coefficients_integral_28e5cd7552f11de88d809fba849192ceb3e1c18e[1] = { 0 };

ufcx_integral integral_28e5cd7552f11de88d809fba849192ceb3e1c18e =
{
  .enabled_coefficients = enabled_coefficients_integral_28e5cd7552f11de88d809fba849192ceb3e1c18e,
  .tabulate_tensor_float64 = tabulate_tensor_integral_28e5cd7552f11de88d809fba849192ceb3e1c18e,
  .needs_facet_permutations = false,
  .coordinate_element = &element_db2bdbab9112f776c604a1d0c570269039160719,
};

// End of code for integral integral_28e5cd7552f11de88d809fba849192ceb3e1c18e

// Code for form form_23e8bec359607ff07ec837c042b24f0aa7461e20

int original_coefficient_position_form_23e8bec359607ff07ec837c042b24f0aa7461e20[1] = { 0 };
ufcx_dofmap* dofmaps_form_23e8bec359607ff07ec837c042b24f0aa7461e20[2] = { &dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06, &dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06 };
ufcx_finite_element* finite_elements_form_23e8bec359607ff07ec837c042b24f0aa7461e20[2] = { &element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06, &element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06 };

// Return a list of the coefficient names.
const char** coefficient_name_form_23e8bec359607ff07ec837c042b24f0aa7461e20(void)
{
static const char* names[1] = { "w0" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_23e8bec359607ff07ec837c042b24f0aa7461e20(void)
{
static const char* names[4] = { "c0", "c1", "c2", "c3" };
return names;
}

int* integral_ids_form_23e8bec359607ff07ec837c042b24f0aa7461e20(ufcx_integral_type integral_type)
{
static int integral_ids_cell_form_23e8bec359607ff07ec837c042b24f0aa7461e20[1] = { -1 };
static int integral_ids_exterior_facet_form_23e8bec359607ff07ec837c042b24f0aa7461e20[1] = { 2 };
switch (integral_type)
{
case cell:
  return integral_ids_cell_form_23e8bec359607ff07ec837c042b24f0aa7461e20;
case exterior_facet:
  return integral_ids_exterior_facet_form_23e8bec359607ff07ec837c042b24f0aa7461e20;
default:
  return NULL;
}
}

int num_integrals_form_23e8bec359607ff07ec837c042b24f0aa7461e20(ufcx_integral_type integral_type)
{
switch (integral_type)
{
case cell:
  return 1;
case interior_facet:
  return 0;
case exterior_facet:
  return 1;
default:
  return 0;
}
}

ufcx_integral** integrals_form_23e8bec359607ff07ec837c042b24f0aa7461e20(ufcx_integral_type integral_type)
{
static ufcx_integral* integrals_cell_form_23e8bec359607ff07ec837c042b24f0aa7461e20[1] = { &integral_8aae8a7f0cf6672b5c4900cbdd52d6915ffea22c };
static ufcx_integral* integrals_exterior_facet_form_23e8bec359607ff07ec837c042b24f0aa7461e20[1] = { &integral_28e5cd7552f11de88d809fba849192ceb3e1c18e };
switch (integral_type)
{
case cell:
  return integrals_cell_form_23e8bec359607ff07ec837c042b24f0aa7461e20;
case exterior_facet:
  return integrals_exterior_facet_form_23e8bec359607ff07ec837c042b24f0aa7461e20;
default:
  return NULL;
}
}

ufcx_form form_23e8bec359607ff07ec837c042b24f0aa7461e20 =
{

  .signature = "78b0280ec9647d6f5d7a3749f19d7d3079b0434a090033c3ef40a18d5ae49c0b0fe25d5ce7ab4f029c62fb15658999032f2039c3f428109cb55144c1aae427a3",
  .rank = 1,
  .num_coefficients = 1,
  .num_constants = 4,
  .original_coefficient_position = original_coefficient_position_form_23e8bec359607ff07ec837c042b24f0aa7461e20,

  .coefficient_name_map = coefficient_name_form_23e8bec359607ff07ec837c042b24f0aa7461e20,
  .constant_name_map = constant_name_form_23e8bec359607ff07ec837c042b24f0aa7461e20,

  .finite_elements = finite_elements_form_23e8bec359607ff07ec837c042b24f0aa7461e20,
  .dofmaps = dofmaps_form_23e8bec359607ff07ec837c042b24f0aa7461e20,

  .integral_ids = integral_ids_form_23e8bec359607ff07ec837c042b24f0aa7461e20,
  .num_integrals = num_integrals_form_23e8bec359607ff07ec837c042b24f0aa7461e20,

  .integrals = integrals_form_23e8bec359607ff07ec837c042b24f0aa7461e20
};

// Alias name
ufcx_form* form_libffcx_forms_9def4e371cc5aba1d0195461047b33b7f1d0186f_0 = &form_23e8bec359607ff07ec837c042b24f0aa7461e20;

ufcx_function_space* functionspace_form_libffcx_forms_9def4e371cc5aba1d0195461047b33b7f1d0186f_0(const char* function_name)
{
static ufcx_function_space functionspace_v_0 =
{
.finite_element = &element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
.dofmap = &dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 3,
.geometry_basix_variant = 0
};
static ufcx_function_space functionspace_f =
{
.finite_element = &element_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
.dofmap = &dofmap_7ac35b579d958db4ebcdc26be7a97d7dea7dde06,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 3,
.geometry_basix_variant = 0
};
if (strcmp(function_name, "v_0") == 0)
  return &functionspace_v_0;
else if (strcmp(function_name, "f") == 0)
  return &functionspace_f;
return NULL;

}

// End of code for form form_23e8bec359607ff07ec837c042b24f0aa7461e20


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 59), // char const * *()(void)
/*  1 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION, 44), // int *()(ufcx_integral_type)
/*  3 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // ufcx_integral_type
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION, 45), // int()(ufcx_integral_type)
/*  6 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION, 81), // ufcx_integral * *()(ufcx_integral_type)
/*  9 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/* 12 */ _CFFI_OP(_CFFI_OP_POINTER, 63), // double *
/* 13 */ _CFFI_OP(_CFFI_OP_POINTER, 63), // double const *
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 16 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // int const *
/* 17 */ _CFFI_OP(_CFFI_OP_POINTER, 85), // uint8_t const *
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 19 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *)
/* 20 */ _CFFI_OP(_CFFI_OP_POINTER, 62), // double _Complex *
/* 21 */ _CFFI_OP(_CFFI_OP_POINTER, 62), // double _Complex const *
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 21),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 17),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 65), // float *
/* 29 */ _CFFI_OP(_CFFI_OP_POINTER, 65), // float const *
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 29),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 29),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 17),
/* 34 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *)
/* 36 */ _CFFI_OP(_CFFI_OP_POINTER, 64), // float _Complex *
/* 37 */ _CFFI_OP(_CFFI_OP_POINTER, 64), // float _Complex const *
/* 38 */ _CFFI_OP(_CFFI_OP_NOOP, 37),
/* 39 */ _CFFI_OP(_CFFI_OP_NOOP, 29),
/* 40 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 41 */ _CFFI_OP(_CFFI_OP_NOOP, 17),
/* 42 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 43 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(int *, int, int)
/* 44 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // int *
/* 45 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 46 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 47 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 48 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(long double *, long double const *, long double const *, long double const *, int const *, uint8_t const *)
/* 49 */ _CFFI_OP(_CFFI_OP_POINTER, 68), // long double *
/* 50 */ _CFFI_OP(_CFFI_OP_POINTER, 68), // long double const *
/* 51 */ _CFFI_OP(_CFFI_OP_NOOP, 50),
/* 52 */ _CFFI_OP(_CFFI_OP_NOOP, 50),
/* 53 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 54 */ _CFFI_OP(_CFFI_OP_NOOP, 17),
/* 55 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 56 */ _CFFI_OP(_CFFI_OP_POINTER, 57), // _Bool const *
/* 57 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 58 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // char const * *(*)(void)
/* 59 */ _CFFI_OP(_CFFI_OP_POINTER, 60), // char const * *
/* 60 */ _CFFI_OP(_CFFI_OP_POINTER, 61), // char const *
/* 61 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 62 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 49), // double _Complex
/* 63 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 64 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 48), // float _Complex
/* 65 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 66 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // int *(*)(ufcx_integral_type)
/* 67 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // int(*)(ufcx_integral_type)
/* 68 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 15), // long double
/* 69 */ _CFFI_OP(_CFFI_OP_POINTER, 70), // ufcx_basix_custom_finite_element *
/* 70 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_basix_custom_finite_element
/* 71 */ _CFFI_OP(_CFFI_OP_POINTER, 72), // ufcx_dofmap * *
/* 72 */ _CFFI_OP(_CFFI_OP_POINTER, 73), // ufcx_dofmap *
/* 73 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_dofmap
/* 74 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_element_type
/* 75 */ _CFFI_OP(_CFFI_OP_POINTER, 76), // ufcx_finite_element * *
/* 76 */ _CFFI_OP(_CFFI_OP_POINTER, 77), // ufcx_finite_element *
/* 77 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // ufcx_finite_element
/* 78 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // ufcx_form
/* 79 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // ufcx_function_space
/* 80 */ _CFFI_OP(_CFFI_OP_POINTER, 8), // ufcx_integral * *(*)(ufcx_integral_type)
/* 81 */ _CFFI_OP(_CFFI_OP_POINTER, 82), // ufcx_integral * *
/* 82 */ _CFFI_OP(_CFFI_OP_POINTER, 83), // ufcx_integral *
/* 83 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // ufcx_integral
/* 84 */ _CFFI_OP(_CFFI_OP_ENUM, 2), // ufcx_shape
/* 85 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 86 */ _CFFI_OP(_CFFI_OP_POINTER, 11), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/* 87 */ _CFFI_OP(_CFFI_OP_POINTER, 19), // void(*)(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *)
/* 88 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // void(*)(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 89 */ _CFFI_OP(_CFFI_OP_POINTER, 35), // void(*)(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *)
/* 90 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // void(*)(int *, int, int)
/* 91 */ _CFFI_OP(_CFFI_OP_POINTER, 48), // void(*)(long double *, long double const *, long double const *, long double const *, int const *, uint8_t const *)
/* 92 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_ufcx_basix_element(unsigned long long *o)
{
  int n = (ufcx_basix_element) <= 0;
  *o = (unsigned long long)((ufcx_basix_element) | 0);  /* check that ufcx_basix_element is an integer */
  return n;
}

static int _cffi_const_ufcx_mixed_element(unsigned long long *o)
{
  int n = (ufcx_mixed_element) <= 0;
  *o = (unsigned long long)((ufcx_mixed_element) | 0);  /* check that ufcx_mixed_element is an integer */
  return n;
}

static int _cffi_const_ufcx_quadrature_element(unsigned long long *o)
{
  int n = (ufcx_quadrature_element) <= 0;
  *o = (unsigned long long)((ufcx_quadrature_element) | 0);  /* check that ufcx_quadrature_element is an integer */
  return n;
}

static int _cffi_const_ufcx_basix_custom_element(unsigned long long *o)
{
  int n = (ufcx_basix_custom_element) <= 0;
  *o = (unsigned long long)((ufcx_basix_custom_element) | 0);  /* check that ufcx_basix_custom_element is an integer */
  return n;
}

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

static int _cffi_const_interval(unsigned long long *o)
{
  int n = (interval) <= 0;
  *o = (unsigned long long)((interval) | 0);  /* check that interval is an integer */
  return n;
}

static int _cffi_const_triangle(unsigned long long *o)
{
  int n = (triangle) <= 0;
  *o = (unsigned long long)((triangle) | 0);  /* check that triangle is an integer */
  return n;
}

static int _cffi_const_quadrilateral(unsigned long long *o)
{
  int n = (quadrilateral) <= 0;
  *o = (unsigned long long)((quadrilateral) | 0);  /* check that quadrilateral is an integer */
  return n;
}

static int _cffi_const_tetrahedron(unsigned long long *o)
{
  int n = (tetrahedron) <= 0;
  *o = (unsigned long long)((tetrahedron) | 0);  /* check that tetrahedron is an integer */
  return n;
}

static int _cffi_const_hexahedron(unsigned long long *o)
{
  int n = (hexahedron) <= 0;
  *o = (unsigned long long)((hexahedron) | 0);  /* check that hexahedron is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

static int _cffi_const_prism(unsigned long long *o)
{
  int n = (prism) <= 0;
  *o = (unsigned long long)((prism) | 0);  /* check that prism is an integer */
  return n;
}

static int _cffi_const_pyramid(unsigned long long *o)
{
  int n = (pyramid) <= 0;
  *o = (unsigned long long)((pyramid) | 0);  /* check that pyramid is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_dofmap(ufcx_dofmap *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->num_global_support_dofs) | 0);  /* check that 'ufcx_dofmap.num_global_support_dofs' is an integer */
  (void)((p->num_element_support_dofs) | 0);  /* check that 'ufcx_dofmap.num_element_support_dofs' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufcx_dofmap.block_size' is an integer */
  { int * *tmp = &p->num_entity_dofs; (void)tmp; }
  { void(* *tmp)(int *, int, int) = &p->tabulate_entity_dofs; (void)tmp; }
  { int * *tmp = &p->num_entity_closure_dofs; (void)tmp; }
  { void(* *tmp)(int *, int, int) = &p->tabulate_entity_closure_dofs; (void)tmp; }
  (void)((p->num_sub_dofmaps) | 0);  /* check that 'ufcx_dofmap.num_sub_dofmaps' is an integer */
  { ufcx_dofmap * * *tmp = &p->sub_dofmaps; (void)tmp; }
}
struct _cffi_align__ufcx_dofmap { char x; ufcx_dofmap y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_finite_element(ufcx_finite_element *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  { ufcx_shape *tmp = &p->cell_shape; (void)tmp; }
  { ufcx_element_type *tmp = &p->element_type; (void)tmp; }
  (void)((p->topological_dimension) | 0);  /* check that 'ufcx_finite_element.topological_dimension' is an integer */
  (void)((p->geometric_dimension) | 0);  /* check that 'ufcx_finite_element.geometric_dimension' is an integer */
  (void)((p->space_dimension) | 0);  /* check that 'ufcx_finite_element.space_dimension' is an integer */
  (void)((p->value_rank) | 0);  /* check that 'ufcx_finite_element.value_rank' is an integer */
  { int * *tmp = &p->value_shape; (void)tmp; }
  (void)((p->value_size) | 0);  /* check that 'ufcx_finite_element.value_size' is an integer */
  (void)((p->reference_value_rank) | 0);  /* check that 'ufcx_finite_element.reference_value_rank' is an integer */
  { int * *tmp = &p->reference_value_shape; (void)tmp; }
  (void)((p->reference_value_size) | 0);  /* check that 'ufcx_finite_element.reference_value_size' is an integer */
  (void)((p->degree) | 0);  /* check that 'ufcx_finite_element.degree' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufcx_finite_element.block_size' is an integer */
  { char const * *tmp = &p->family; (void)tmp; }
  (void)((p->basix_family) | 0);  /* check that 'ufcx_finite_element.basix_family' is an integer */
  (void)((p->basix_cell) | 0);  /* check that 'ufcx_finite_element.basix_cell' is an integer */
  (void)((p->discontinuous) | 0);  /* check that 'ufcx_finite_element.discontinuous' is an integer */
  (void)((p->lagrange_variant) | 0);  /* check that 'ufcx_finite_element.lagrange_variant' is an integer */
  (void)((p->dpc_variant) | 0);  /* check that 'ufcx_finite_element.dpc_variant' is an integer */
  (void)((p->num_sub_elements) | 0);  /* check that 'ufcx_finite_element.num_sub_elements' is an integer */
  { ufcx_finite_element * * *tmp = &p->sub_elements; (void)tmp; }
  { ufcx_basix_custom_finite_element * *tmp = &p->custom_element; (void)tmp; }
}
struct _cffi_align__ufcx_finite_element { char x; ufcx_finite_element y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_form(ufcx_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufcx_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufcx_form.num_coefficients' is an integer */
  (void)((p->num_constants) | 0);  /* check that 'ufcx_form.num_constants' is an integer */
  { int * *tmp = &p->original_coefficient_position; (void)tmp; }
  { char const * *(* *tmp)(void) = &p->coefficient_name_map; (void)tmp; }
  { char const * *(* *tmp)(void) = &p->constant_name_map; (void)tmp; }
  { ufcx_finite_element * * *tmp = &p->finite_elements; (void)tmp; }
  { ufcx_dofmap * * *tmp = &p->dofmaps; (void)tmp; }
  { int *(* *tmp)(ufcx_integral_type) = &p->integral_ids; (void)tmp; }
  { int(* *tmp)(ufcx_integral_type) = &p->num_integrals; (void)tmp; }
  { ufcx_integral * *(* *tmp)(ufcx_integral_type) = &p->integrals; (void)tmp; }
}
struct _cffi_align__ufcx_form { char x; ufcx_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_integral(ufcx_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(float *, float const *, float const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_float32; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_float64; (void)tmp; }
  { void(* *tmp)(long double *, long double const *, long double const *, long double const *, int const *, uint8_t const *) = &p->tabulate_tensor_longdouble; (void)tmp; }
  { void(* *tmp)(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex64; (void)tmp; }
  { void(* *tmp)(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex128; (void)tmp; }
  (void)((p->needs_facet_permutations) | 0);  /* check that 'ufcx_integral.needs_facet_permutations' is an integer */
  { ufcx_finite_element * *tmp = &p->coordinate_element; (void)tmp; }
}
struct _cffi_align__ufcx_integral { char x; ufcx_integral y; };

static ufcx_form *_cffi_var_form_23e8bec359607ff07ec837c042b24f0aa7461e20(void)
{
  return &(form_23e8bec359607ff07ec837c042b24f0aa7461e20);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_23e8bec359607ff07ec837c042b24f0aa7461e20", (void *)_cffi_var_form_23e8bec359607ff07ec837c042b24f0aa7461e20, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 78), (void *)0 },
  { "hexahedron", (void *)_cffi_const_hexahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interval", (void *)_cffi_const_interval, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "prism", (void *)_cffi_const_prism, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "pyramid", (void *)_cffi_const_pyramid, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "quadrilateral", (void *)_cffi_const_quadrilateral, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "tetrahedron", (void *)_cffi_const_tetrahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "triangle", (void *)_cffi_const_triangle, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_basix_custom_element", (void *)_cffi_const_ufcx_basix_custom_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_basix_element", (void *)_cffi_const_ufcx_basix_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_mixed_element", (void *)_cffi_const_ufcx_mixed_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_quadrature_element", (void *)_cffi_const_ufcx_quadrature_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_dofmap, signature),
                 sizeof(((ufcx_dofmap *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "num_global_support_dofs", offsetof(ufcx_dofmap, num_global_support_dofs),
                               sizeof(((ufcx_dofmap *)0)->num_global_support_dofs),
                               _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_element_support_dofs", offsetof(ufcx_dofmap, num_element_support_dofs),
                                sizeof(((ufcx_dofmap *)0)->num_element_support_dofs),
                                _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "block_size", offsetof(ufcx_dofmap, block_size),
                  sizeof(((ufcx_dofmap *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_entity_dofs", offsetof(ufcx_dofmap, num_entity_dofs),
                       sizeof(((ufcx_dofmap *)0)->num_entity_dofs),
                       _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "tabulate_entity_dofs", offsetof(ufcx_dofmap, tabulate_entity_dofs),
                            sizeof(((ufcx_dofmap *)0)->tabulate_entity_dofs),
                            _CFFI_OP(_CFFI_OP_NOOP, 90) },
  { "num_entity_closure_dofs", offsetof(ufcx_dofmap, num_entity_closure_dofs),
                               sizeof(((ufcx_dofmap *)0)->num_entity_closure_dofs),
                               _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "tabulate_entity_closure_dofs", offsetof(ufcx_dofmap, tabulate_entity_closure_dofs),
                                    sizeof(((ufcx_dofmap *)0)->tabulate_entity_closure_dofs),
                                    _CFFI_OP(_CFFI_OP_NOOP, 90) },
  { "num_sub_dofmaps", offsetof(ufcx_dofmap, num_sub_dofmaps),
                       sizeof(((ufcx_dofmap *)0)->num_sub_dofmaps),
                       _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "sub_dofmaps", offsetof(ufcx_dofmap, sub_dofmaps),
                   sizeof(((ufcx_dofmap *)0)->sub_dofmaps),
                   _CFFI_OP(_CFFI_OP_NOOP, 71) },
  { "signature", offsetof(ufcx_finite_element, signature),
                 sizeof(((ufcx_finite_element *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "cell_shape", offsetof(ufcx_finite_element, cell_shape),
                  sizeof(((ufcx_finite_element *)0)->cell_shape),
                  _CFFI_OP(_CFFI_OP_NOOP, 84) },
  { "element_type", offsetof(ufcx_finite_element, element_type),
                    sizeof(((ufcx_finite_element *)0)->element_type),
                    _CFFI_OP(_CFFI_OP_NOOP, 74) },
  { "topological_dimension", offsetof(ufcx_finite_element, topological_dimension),
                             sizeof(((ufcx_finite_element *)0)->topological_dimension),
                             _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "geometric_dimension", offsetof(ufcx_finite_element, geometric_dimension),
                           sizeof(((ufcx_finite_element *)0)->geometric_dimension),
                           _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "space_dimension", offsetof(ufcx_finite_element, space_dimension),
                       sizeof(((ufcx_finite_element *)0)->space_dimension),
                       _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "value_rank", offsetof(ufcx_finite_element, value_rank),
                  sizeof(((ufcx_finite_element *)0)->value_rank),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "value_shape", offsetof(ufcx_finite_element, value_shape),
                   sizeof(((ufcx_finite_element *)0)->value_shape),
                   _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "value_size", offsetof(ufcx_finite_element, value_size),
                  sizeof(((ufcx_finite_element *)0)->value_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "reference_value_rank", offsetof(ufcx_finite_element, reference_value_rank),
                            sizeof(((ufcx_finite_element *)0)->reference_value_rank),
                            _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "reference_value_shape", offsetof(ufcx_finite_element, reference_value_shape),
                             sizeof(((ufcx_finite_element *)0)->reference_value_shape),
                             _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "reference_value_size", offsetof(ufcx_finite_element, reference_value_size),
                            sizeof(((ufcx_finite_element *)0)->reference_value_size),
                            _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "degree", offsetof(ufcx_finite_element, degree),
              sizeof(((ufcx_finite_element *)0)->degree),
              _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "block_size", offsetof(ufcx_finite_element, block_size),
                  sizeof(((ufcx_finite_element *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "family", offsetof(ufcx_finite_element, family),
              sizeof(((ufcx_finite_element *)0)->family),
              _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "basix_family", offsetof(ufcx_finite_element, basix_family),
                    sizeof(((ufcx_finite_element *)0)->basix_family),
                    _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "basix_cell", offsetof(ufcx_finite_element, basix_cell),
                  sizeof(((ufcx_finite_element *)0)->basix_cell),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "discontinuous", offsetof(ufcx_finite_element, discontinuous),
                     sizeof(((ufcx_finite_element *)0)->discontinuous),
                     _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "lagrange_variant", offsetof(ufcx_finite_element, lagrange_variant),
                        sizeof(((ufcx_finite_element *)0)->lagrange_variant),
                        _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "dpc_variant", offsetof(ufcx_finite_element, dpc_variant),
                   sizeof(((ufcx_finite_element *)0)->dpc_variant),
                   _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_sub_elements", offsetof(ufcx_finite_element, num_sub_elements),
                        sizeof(((ufcx_finite_element *)0)->num_sub_elements),
                        _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "sub_elements", offsetof(ufcx_finite_element, sub_elements),
                    sizeof(((ufcx_finite_element *)0)->sub_elements),
                    _CFFI_OP(_CFFI_OP_NOOP, 75) },
  { "custom_element", offsetof(ufcx_finite_element, custom_element),
                      sizeof(((ufcx_finite_element *)0)->custom_element),
                      _CFFI_OP(_CFFI_OP_NOOP, 69) },
  { "signature", offsetof(ufcx_form, signature),
                 sizeof(((ufcx_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "rank", offsetof(ufcx_form, rank),
            sizeof(((ufcx_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_coefficients", offsetof(ufcx_form, num_coefficients),
                        sizeof(((ufcx_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_constants", offsetof(ufcx_form, num_constants),
                     sizeof(((ufcx_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "original_coefficient_position", offsetof(ufcx_form, original_coefficient_position),
                                     sizeof(((ufcx_form *)0)->original_coefficient_position),
                                     _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "coefficient_name_map", offsetof(ufcx_form, coefficient_name_map),
                            sizeof(((ufcx_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "constant_name_map", offsetof(ufcx_form, constant_name_map),
                         sizeof(((ufcx_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "finite_elements", offsetof(ufcx_form, finite_elements),
                       sizeof(((ufcx_form *)0)->finite_elements),
                       _CFFI_OP(_CFFI_OP_NOOP, 75) },
  { "dofmaps", offsetof(ufcx_form, dofmaps),
               sizeof(((ufcx_form *)0)->dofmaps),
               _CFFI_OP(_CFFI_OP_NOOP, 71) },
  { "integral_ids", offsetof(ufcx_form, integral_ids),
                    sizeof(((ufcx_form *)0)->integral_ids),
                    _CFFI_OP(_CFFI_OP_NOOP, 66) },
  { "num_integrals", offsetof(ufcx_form, num_integrals),
                     sizeof(((ufcx_form *)0)->num_integrals),
                     _CFFI_OP(_CFFI_OP_NOOP, 67) },
  { "integrals", offsetof(ufcx_form, integrals),
                 sizeof(((ufcx_form *)0)->integrals),
                 _CFFI_OP(_CFFI_OP_NOOP, 80) },
  { "enabled_coefficients", offsetof(ufcx_integral, enabled_coefficients),
                            sizeof(((ufcx_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "tabulate_tensor_float32", offsetof(ufcx_integral, tabulate_tensor_float32),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float32),
                               _CFFI_OP(_CFFI_OP_NOOP, 88) },
  { "tabulate_tensor_float64", offsetof(ufcx_integral, tabulate_tensor_float64),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float64),
                               _CFFI_OP(_CFFI_OP_NOOP, 86) },
  { "tabulate_tensor_longdouble", offsetof(ufcx_integral, tabulate_tensor_longdouble),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_longdouble),
                                  _CFFI_OP(_CFFI_OP_NOOP, 91) },
  { "tabulate_tensor_complex64", offsetof(ufcx_integral, tabulate_tensor_complex64),
                                 sizeof(((ufcx_integral *)0)->tabulate_tensor_complex64),
                                 _CFFI_OP(_CFFI_OP_NOOP, 89) },
  { "tabulate_tensor_complex128", offsetof(ufcx_integral, tabulate_tensor_complex128),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_complex128),
                                  _CFFI_OP(_CFFI_OP_NOOP, 87) },
  { "needs_facet_permutations", offsetof(ufcx_integral, needs_facet_permutations),
                                sizeof(((ufcx_integral *)0)->needs_facet_permutations),
                                _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "coordinate_element", offsetof(ufcx_integral, coordinate_element),
                          sizeof(((ufcx_integral *)0)->coordinate_element),
                          _CFFI_OP(_CFFI_OP_NOOP, 76) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_basix_custom_finite_element", 70, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ufcx_dofmap", 73, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_dofmap), offsetof(struct _cffi_align__ufcx_dofmap, y), 0, 10 },
  { "ufcx_finite_element", 77, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_finite_element), offsetof(struct _cffi_align__ufcx_finite_element, y), 10, 23 },
  { "ufcx_form", 78, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_form), offsetof(struct _cffi_align__ufcx_form, y), 33, 12 },
  { "ufcx_function_space", 79, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ufcx_integral", 83, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_integral), offsetof(struct _cffi_align__ufcx_integral, y), 45, 8 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_element_type", 74, _cffi_prim_int(sizeof(ufcx_element_type), ((ufcx_element_type)-1) <= 0),
    "ufcx_basix_element,ufcx_mixed_element,ufcx_quadrature_element,ufcx_basix_custom_element" },
  { "$ufcx_integral_type", 3, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet" },
  { "$ufcx_shape", 84, _cffi_prim_int(sizeof(ufcx_shape), ((ufcx_shape)-1) <= 0),
    "interval,triangle,quadrilateral,tetrahedron,hexahedron,vertex,prism,pyramid" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_basix_custom_finite_element", 70 },
  { "ufcx_dofmap", 73 },
  { "ufcx_element_type", 74 },
  { "ufcx_finite_element", 77 },
  { "ufcx_form", 78 },
  { "ufcx_function_space", 79 },
  { "ufcx_integral", 83 },
  { "ufcx_integral_type", 3 },
  { "ufcx_shape", 84 },
  { "ufcx_tabulate_tensor_complex128", 19 },
  { "ufcx_tabulate_tensor_complex64", 35 },
  { "ufcx_tabulate_tensor_float32", 27 },
  { "ufcx_tabulate_tensor_float64", 11 },
  { "ufcx_tabulate_tensor_longdouble", 48 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  16,  /* num_globals */
  6,  /* num_struct_unions */
  3,  /* num_enums */
  14,  /* num_typenames */
  NULL,  /* no includes */
  93,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_9def4e371cc5aba1d0195461047b33b7f1d0186f(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffcx_forms_9def4e371cc5aba1d0195461047b33b7f1d0186f(void) { return NULL; }
#  else
     initlibffcx_forms_9def4e371cc5aba1d0195461047b33b7f1d0186f(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffcx_forms_9def4e371cc5aba1d0195461047b33b7f1d0186f(void)
{
  return _cffi_init("libffcx_forms_9def4e371cc5aba1d0195461047b33b7f1d0186f", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffcx_forms_9def4e371cc5aba1d0195461047b33b7f1d0186f(void)
{
  _cffi_init("libffcx_forms_9def4e371cc5aba1d0195461047b33b7f1d0186f", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
