#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.6.0.dev0.
//
// This code was generated with the following options:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'padlen': 1,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'verbosity': 30}


#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>

// Code for element element_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92






ufcx_finite_element element_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92 =
{
  .signature = "Basix element (P, tetrahedron, 2, gll_warped, unset, False)",
  .cell_shape = tetrahedron,
  .element_type = ufcx_basix_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 10,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 2,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 3,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92

// Code for element element_11fc75d1c76d46d3b31909371f4d9176cc28b57f

int value_shape_element_11fc75d1c76d46d3b31909371f4d9176cc28b57f[1] = { 3 };
int reference_value_shape_element_11fc75d1c76d46d3b31909371f4d9176cc28b57f[1] = { 3 };
ufcx_finite_element* sub_elements_element_11fc75d1c76d46d3b31909371f4d9176cc28b57f[3] = { &element_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92, &element_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92, &element_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92 };


ufcx_finite_element element_11fc75d1c76d46d3b31909371f4d9176cc28b57f =
{
  .signature = "VectorElement(Basix element (P, tetrahedron, 2, gll_warped, unset, False), 3)",
  .cell_shape = tetrahedron,
  .element_type = ufcx_basix_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 30,
  .value_rank = 1,
  .value_shape = value_shape_element_11fc75d1c76d46d3b31909371f4d9176cc28b57f,
  .value_size = 3,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_11fc75d1c76d46d3b31909371f4d9176cc28b57f,
  .reference_value_size = 3,
  .degree = 2,
  .block_size = 3,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 3,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 3,
  .sub_elements = sub_elements_element_11fc75d1c76d46d3b31909371f4d9176cc28b57f,
  .custom_element = NULL
};

// End of code for element element_11fc75d1c76d46d3b31909371f4d9176cc28b57f

// Code for dofmap dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92



void tabulate_entity_dofs_dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 4;
    break;
  case 1:
    dofs[0] = 5;
    break;
  case 2:
    dofs[0] = 6;
    break;
  case 3:
    dofs[0] = 7;
    break;
  case 4:
    dofs[0] = 8;
    break;
  case 5:
    dofs[0] = 9;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 2;
    dofs[1] = 3;
    dofs[2] = 4;
    break;
  case 1:
    dofs[0] = 1;
    dofs[1] = 3;
    dofs[2] = 5;
    break;
  case 2:
    dofs[0] = 1;
    dofs[1] = 2;
    dofs[2] = 6;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 3;
    dofs[2] = 7;
    break;
  case 4:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 8;
    break;
  case 5:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 9;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    dofs[2] = 3;
    dofs[3] = 4;
    dofs[4] = 5;
    dofs[5] = 6;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 3;
    dofs[3] = 4;
    dofs[4] = 7;
    dofs[5] = 8;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 3;
    dofs[3] = 5;
    dofs[4] = 7;
    dofs[5] = 9;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 6;
    dofs[4] = 8;
    dofs[5] = 9;
    break;
  }
  break;
case 3:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    dofs[4] = 4;
    dofs[5] = 5;
    dofs[6] = 6;
    dofs[7] = 7;
    dofs[8] = 8;
    dofs[9] = 9;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92[4] = { 1, 1, 0, 0 };

int num_entity_closure_dofs_dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92[4] = { 1, 3, 6, 10 };

ufcx_dofmap dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92 =
{
  .signature = "FFCx dofmap for Basix element (P, tetrahedron, 2, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 10,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92

// Code for dofmap dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f

ufcx_dofmap* sub_dofmaps_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f[3] = { &dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92, &dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92, &dofmap_98d9c4b0159fb21e1599a0fd2fb04245e6c9ad92 };

void tabulate_entity_dofs_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 4;
    break;
  case 1:
    dofs[0] = 5;
    break;
  case 2:
    dofs[0] = 6;
    break;
  case 3:
    dofs[0] = 7;
    break;
  case 4:
    dofs[0] = 8;
    break;
  case 5:
    dofs[0] = 9;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 2;
    dofs[1] = 3;
    dofs[2] = 4;
    break;
  case 1:
    dofs[0] = 1;
    dofs[1] = 3;
    dofs[2] = 5;
    break;
  case 2:
    dofs[0] = 1;
    dofs[1] = 2;
    dofs[2] = 6;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 3;
    dofs[2] = 7;
    break;
  case 4:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 8;
    break;
  case 5:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 9;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    dofs[2] = 3;
    dofs[3] = 4;
    dofs[4] = 5;
    dofs[5] = 6;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 3;
    dofs[3] = 4;
    dofs[4] = 7;
    dofs[5] = 8;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 3;
    dofs[3] = 5;
    dofs[4] = 7;
    dofs[5] = 9;
    break;
  case 3:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 6;
    dofs[4] = 8;
    dofs[5] = 9;
    break;
  }
  break;
case 3:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    dofs[4] = 4;
    dofs[5] = 5;
    dofs[6] = 6;
    dofs[7] = 7;
    dofs[8] = 8;
    dofs[9] = 9;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f[4] = { 1, 1, 0, 0 };

int num_entity_closure_dofs_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f[4] = { 1, 3, 6, 10 };

ufcx_dofmap dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f =
{
  .signature = "FFCx dofmap for VectorElement(Basix element (P, tetrahedron, 2, gll_warped, unset, False), 3)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 10,
  .block_size = 3,
  .num_entity_dofs = num_entity_dofs_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f,
  .num_sub_dofmaps = 3,
  .sub_dofmaps = sub_dofmaps_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f
};

// End of code for dofmap dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 21), // void()(int *, int, int)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // int *
/*  2 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  3 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 7), // char const *
/*  7 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/*  8 */ _CFFI_OP(_CFFI_OP_POINTER, 9), // ufcx_basix_custom_finite_element *
/*  9 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_basix_custom_finite_element
/* 10 */ _CFFI_OP(_CFFI_OP_POINTER, 11), // ufcx_dofmap * *
/* 11 */ _CFFI_OP(_CFFI_OP_POINTER, 12), // ufcx_dofmap *
/* 12 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_dofmap
/* 13 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_element_type
/* 14 */ _CFFI_OP(_CFFI_OP_POINTER, 15), // ufcx_finite_element * *
/* 15 */ _CFFI_OP(_CFFI_OP_POINTER, 16), // ufcx_finite_element *
/* 16 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // ufcx_finite_element
/* 17 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // ufcx_function_space
/* 18 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // ufcx_integral_type
/* 19 */ _CFFI_OP(_CFFI_OP_ENUM, 2), // ufcx_shape
/* 20 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // void(*)(int *, int, int)
/* 21 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_ufcx_basix_element(unsigned long long *o)
{
  int n = (ufcx_basix_element) <= 0;
  *o = (unsigned long long)((ufcx_basix_element) | 0);  /* check that ufcx_basix_element is an integer */
  return n;
}

static int _cffi_const_ufcx_mixed_element(unsigned long long *o)
{
  int n = (ufcx_mixed_element) <= 0;
  *o = (unsigned long long)((ufcx_mixed_element) | 0);  /* check that ufcx_mixed_element is an integer */
  return n;
}

static int _cffi_const_ufcx_quadrature_element(unsigned long long *o)
{
  int n = (ufcx_quadrature_element) <= 0;
  *o = (unsigned long long)((ufcx_quadrature_element) | 0);  /* check that ufcx_quadrature_element is an integer */
  return n;
}

static int _cffi_const_ufcx_basix_custom_element(unsigned long long *o)
{
  int n = (ufcx_basix_custom_element) <= 0;
  *o = (unsigned long long)((ufcx_basix_custom_element) | 0);  /* check that ufcx_basix_custom_element is an integer */
  return n;
}

static int _cffi_const_ufcx_real_element(unsigned long long *o)
{
  int n = (ufcx_real_element) <= 0;
  *o = (unsigned long long)((ufcx_real_element) | 0);  /* check that ufcx_real_element is an integer */
  return n;
}

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

static int _cffi_const_interval(unsigned long long *o)
{
  int n = (interval) <= 0;
  *o = (unsigned long long)((interval) | 0);  /* check that interval is an integer */
  return n;
}

static int _cffi_const_triangle(unsigned long long *o)
{
  int n = (triangle) <= 0;
  *o = (unsigned long long)((triangle) | 0);  /* check that triangle is an integer */
  return n;
}

static int _cffi_const_quadrilateral(unsigned long long *o)
{
  int n = (quadrilateral) <= 0;
  *o = (unsigned long long)((quadrilateral) | 0);  /* check that quadrilateral is an integer */
  return n;
}

static int _cffi_const_tetrahedron(unsigned long long *o)
{
  int n = (tetrahedron) <= 0;
  *o = (unsigned long long)((tetrahedron) | 0);  /* check that tetrahedron is an integer */
  return n;
}

static int _cffi_const_hexahedron(unsigned long long *o)
{
  int n = (hexahedron) <= 0;
  *o = (unsigned long long)((hexahedron) | 0);  /* check that hexahedron is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

static int _cffi_const_prism(unsigned long long *o)
{
  int n = (prism) <= 0;
  *o = (unsigned long long)((prism) | 0);  /* check that prism is an integer */
  return n;
}

static int _cffi_const_pyramid(unsigned long long *o)
{
  int n = (pyramid) <= 0;
  *o = (unsigned long long)((pyramid) | 0);  /* check that pyramid is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_dofmap(ufcx_dofmap *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->num_global_support_dofs) | 0);  /* check that 'ufcx_dofmap.num_global_support_dofs' is an integer */
  (void)((p->num_element_support_dofs) | 0);  /* check that 'ufcx_dofmap.num_element_support_dofs' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufcx_dofmap.block_size' is an integer */
  { int * *tmp = &p->num_entity_dofs; (void)tmp; }
  { void(* *tmp)(int *, int, int) = &p->tabulate_entity_dofs; (void)tmp; }
  { int * *tmp = &p->num_entity_closure_dofs; (void)tmp; }
  { void(* *tmp)(int *, int, int) = &p->tabulate_entity_closure_dofs; (void)tmp; }
  (void)((p->num_sub_dofmaps) | 0);  /* check that 'ufcx_dofmap.num_sub_dofmaps' is an integer */
  { ufcx_dofmap * * *tmp = &p->sub_dofmaps; (void)tmp; }
}
struct _cffi_align__ufcx_dofmap { char x; ufcx_dofmap y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_finite_element(ufcx_finite_element *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  { ufcx_shape *tmp = &p->cell_shape; (void)tmp; }
  { ufcx_element_type *tmp = &p->element_type; (void)tmp; }
  (void)((p->topological_dimension) | 0);  /* check that 'ufcx_finite_element.topological_dimension' is an integer */
  (void)((p->geometric_dimension) | 0);  /* check that 'ufcx_finite_element.geometric_dimension' is an integer */
  (void)((p->space_dimension) | 0);  /* check that 'ufcx_finite_element.space_dimension' is an integer */
  (void)((p->value_rank) | 0);  /* check that 'ufcx_finite_element.value_rank' is an integer */
  { int * *tmp = &p->value_shape; (void)tmp; }
  (void)((p->value_size) | 0);  /* check that 'ufcx_finite_element.value_size' is an integer */
  (void)((p->reference_value_rank) | 0);  /* check that 'ufcx_finite_element.reference_value_rank' is an integer */
  { int * *tmp = &p->reference_value_shape; (void)tmp; }
  (void)((p->reference_value_size) | 0);  /* check that 'ufcx_finite_element.reference_value_size' is an integer */
  (void)((p->degree) | 0);  /* check that 'ufcx_finite_element.degree' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufcx_finite_element.block_size' is an integer */
  { char const * *tmp = &p->family; (void)tmp; }
  (void)((p->basix_family) | 0);  /* check that 'ufcx_finite_element.basix_family' is an integer */
  (void)((p->basix_cell) | 0);  /* check that 'ufcx_finite_element.basix_cell' is an integer */
  (void)((p->discontinuous) | 0);  /* check that 'ufcx_finite_element.discontinuous' is an integer */
  (void)((p->lagrange_variant) | 0);  /* check that 'ufcx_finite_element.lagrange_variant' is an integer */
  (void)((p->dpc_variant) | 0);  /* check that 'ufcx_finite_element.dpc_variant' is an integer */
  (void)((p->num_sub_elements) | 0);  /* check that 'ufcx_finite_element.num_sub_elements' is an integer */
  { ufcx_finite_element * * *tmp = &p->sub_elements; (void)tmp; }
  { ufcx_basix_custom_finite_element * *tmp = &p->custom_element; (void)tmp; }
}
struct _cffi_align__ufcx_finite_element { char x; ufcx_finite_element y; };

static ufcx_dofmap *_cffi_var_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f(void)
{
  return &(dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f);
}

static ufcx_finite_element *_cffi_var_element_11fc75d1c76d46d3b31909371f4d9176cc28b57f(void)
{
  return &(element_11fc75d1c76d46d3b31909371f4d9176cc28b57f);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f", (void *)_cffi_var_dofmap_11fc75d1c76d46d3b31909371f4d9176cc28b57f, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 12), (void *)0 },
  { "element_11fc75d1c76d46d3b31909371f4d9176cc28b57f", (void *)_cffi_var_element_11fc75d1c76d46d3b31909371f4d9176cc28b57f, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 16), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "hexahedron", (void *)_cffi_const_hexahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interval", (void *)_cffi_const_interval, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "prism", (void *)_cffi_const_prism, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "pyramid", (void *)_cffi_const_pyramid, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "quadrilateral", (void *)_cffi_const_quadrilateral, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "tetrahedron", (void *)_cffi_const_tetrahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "triangle", (void *)_cffi_const_triangle, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_basix_custom_element", (void *)_cffi_const_ufcx_basix_custom_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_basix_element", (void *)_cffi_const_ufcx_basix_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_mixed_element", (void *)_cffi_const_ufcx_mixed_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_quadrature_element", (void *)_cffi_const_ufcx_quadrature_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_real_element", (void *)_cffi_const_ufcx_real_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_dofmap, signature),
                 sizeof(((ufcx_dofmap *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 6) },
  { "num_global_support_dofs", offsetof(ufcx_dofmap, num_global_support_dofs),
                               sizeof(((ufcx_dofmap *)0)->num_global_support_dofs),
                               _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "num_element_support_dofs", offsetof(ufcx_dofmap, num_element_support_dofs),
                                sizeof(((ufcx_dofmap *)0)->num_element_support_dofs),
                                _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "block_size", offsetof(ufcx_dofmap, block_size),
                  sizeof(((ufcx_dofmap *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "num_entity_dofs", offsetof(ufcx_dofmap, num_entity_dofs),
                       sizeof(((ufcx_dofmap *)0)->num_entity_dofs),
                       _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "tabulate_entity_dofs", offsetof(ufcx_dofmap, tabulate_entity_dofs),
                            sizeof(((ufcx_dofmap *)0)->tabulate_entity_dofs),
                            _CFFI_OP(_CFFI_OP_NOOP, 20) },
  { "num_entity_closure_dofs", offsetof(ufcx_dofmap, num_entity_closure_dofs),
                               sizeof(((ufcx_dofmap *)0)->num_entity_closure_dofs),
                               _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "tabulate_entity_closure_dofs", offsetof(ufcx_dofmap, tabulate_entity_closure_dofs),
                                    sizeof(((ufcx_dofmap *)0)->tabulate_entity_closure_dofs),
                                    _CFFI_OP(_CFFI_OP_NOOP, 20) },
  { "num_sub_dofmaps", offsetof(ufcx_dofmap, num_sub_dofmaps),
                       sizeof(((ufcx_dofmap *)0)->num_sub_dofmaps),
                       _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "sub_dofmaps", offsetof(ufcx_dofmap, sub_dofmaps),
                   sizeof(((ufcx_dofmap *)0)->sub_dofmaps),
                   _CFFI_OP(_CFFI_OP_NOOP, 10) },
  { "signature", offsetof(ufcx_finite_element, signature),
                 sizeof(((ufcx_finite_element *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 6) },
  { "cell_shape", offsetof(ufcx_finite_element, cell_shape),
                  sizeof(((ufcx_finite_element *)0)->cell_shape),
                  _CFFI_OP(_CFFI_OP_NOOP, 19) },
  { "element_type", offsetof(ufcx_finite_element, element_type),
                    sizeof(((ufcx_finite_element *)0)->element_type),
                    _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "topological_dimension", offsetof(ufcx_finite_element, topological_dimension),
                             sizeof(((ufcx_finite_element *)0)->topological_dimension),
                             _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "geometric_dimension", offsetof(ufcx_finite_element, geometric_dimension),
                           sizeof(((ufcx_finite_element *)0)->geometric_dimension),
                           _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "space_dimension", offsetof(ufcx_finite_element, space_dimension),
                       sizeof(((ufcx_finite_element *)0)->space_dimension),
                       _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "value_rank", offsetof(ufcx_finite_element, value_rank),
                  sizeof(((ufcx_finite_element *)0)->value_rank),
                  _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "value_shape", offsetof(ufcx_finite_element, value_shape),
                   sizeof(((ufcx_finite_element *)0)->value_shape),
                   _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "value_size", offsetof(ufcx_finite_element, value_size),
                  sizeof(((ufcx_finite_element *)0)->value_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "reference_value_rank", offsetof(ufcx_finite_element, reference_value_rank),
                            sizeof(((ufcx_finite_element *)0)->reference_value_rank),
                            _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "reference_value_shape", offsetof(ufcx_finite_element, reference_value_shape),
                             sizeof(((ufcx_finite_element *)0)->reference_value_shape),
                             _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "reference_value_size", offsetof(ufcx_finite_element, reference_value_size),
                            sizeof(((ufcx_finite_element *)0)->reference_value_size),
                            _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "degree", offsetof(ufcx_finite_element, degree),
              sizeof(((ufcx_finite_element *)0)->degree),
              _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "block_size", offsetof(ufcx_finite_element, block_size),
                  sizeof(((ufcx_finite_element *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "family", offsetof(ufcx_finite_element, family),
              sizeof(((ufcx_finite_element *)0)->family),
              _CFFI_OP(_CFFI_OP_NOOP, 6) },
  { "basix_family", offsetof(ufcx_finite_element, basix_family),
                    sizeof(((ufcx_finite_element *)0)->basix_family),
                    _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "basix_cell", offsetof(ufcx_finite_element, basix_cell),
                  sizeof(((ufcx_finite_element *)0)->basix_cell),
                  _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "discontinuous", offsetof(ufcx_finite_element, discontinuous),
                     sizeof(((ufcx_finite_element *)0)->discontinuous),
                     _CFFI_OP(_CFFI_OP_NOOP, 5) },
  { "lagrange_variant", offsetof(ufcx_finite_element, lagrange_variant),
                        sizeof(((ufcx_finite_element *)0)->lagrange_variant),
                        _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "dpc_variant", offsetof(ufcx_finite_element, dpc_variant),
                   sizeof(((ufcx_finite_element *)0)->dpc_variant),
                   _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "num_sub_elements", offsetof(ufcx_finite_element, num_sub_elements),
                        sizeof(((ufcx_finite_element *)0)->num_sub_elements),
                        _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "sub_elements", offsetof(ufcx_finite_element, sub_elements),
                    sizeof(((ufcx_finite_element *)0)->sub_elements),
                    _CFFI_OP(_CFFI_OP_NOOP, 14) },
  { "custom_element", offsetof(ufcx_finite_element, custom_element),
                      sizeof(((ufcx_finite_element *)0)->custom_element),
                      _CFFI_OP(_CFFI_OP_NOOP, 8) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_basix_custom_finite_element", 9, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ufcx_dofmap", 12, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_dofmap), offsetof(struct _cffi_align__ufcx_dofmap, y), 0, 10 },
  { "ufcx_finite_element", 16, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_finite_element), offsetof(struct _cffi_align__ufcx_finite_element, y), 10, 23 },
  { "ufcx_function_space", 17, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_element_type", 13, _cffi_prim_int(sizeof(ufcx_element_type), ((ufcx_element_type)-1) <= 0),
    "ufcx_basix_element,ufcx_mixed_element,ufcx_quadrature_element,ufcx_basix_custom_element,ufcx_real_element" },
  { "$ufcx_integral_type", 18, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet" },
  { "$ufcx_shape", 19, _cffi_prim_int(sizeof(ufcx_shape), ((ufcx_shape)-1) <= 0),
    "interval,triangle,quadrilateral,tetrahedron,hexahedron,vertex,prism,pyramid" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_basix_custom_finite_element", 9 },
  { "ufcx_dofmap", 12 },
  { "ufcx_element_type", 13 },
  { "ufcx_finite_element", 16 },
  { "ufcx_function_space", 17 },
  { "ufcx_integral_type", 18 },
  { "ufcx_shape", 19 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  18,  /* num_globals */
  4,  /* num_struct_unions */
  3,  /* num_enums */
  7,  /* num_typenames */
  NULL,  /* no includes */
  22,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_elements_87dc45bbb71a504206f4e29d44c595da463ab411(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffcx_elements_87dc45bbb71a504206f4e29d44c595da463ab411(void) { return NULL; }
#  else
     initlibffcx_elements_87dc45bbb71a504206f4e29d44c595da463ab411(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffcx_elements_87dc45bbb71a504206f4e29d44c595da463ab411(void)
{
  return _cffi_init("libffcx_elements_87dc45bbb71a504206f4e29d44c595da463ab411", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffcx_elements_87dc45bbb71a504206f4e29d44c595da463ab411(void)
{
  _cffi_init("libffcx_elements_87dc45bbb71a504206f4e29d44c595da463ab411", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
